### ISSUE TITLE
Facet and refine search results by subject

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#11]
**Acceptance criteria**

* Index data from the children of `<controlaccess/>`: `<subject/>`, `<function/>`, `<genreform/>`, `<occupation/>`
* Selecting the facet should filter results by the selected value
* [ ] _Question_: Do these need to be indexed into separate fields?

- - -

* Ref: req 1.11
* Category: 1. Core Discovery
* Subcategory: Browse

**Comment by anarchivist** [comment]
87a81e1 adds data for the specific additional fields.

**Comment by jkeck** [comment]
@anarchivist, we notice that the subject shows up under the collection and the component, but it's not specified here which one we want (or if it is both).

The xpath in the current PR indexes any control access sub-elements into the collection (even when they are elements in a component).

**Comment by anarchivist** [comment]
> The xpath in the current PR indexes any control access sub-elements into the collection (even when they are elements in a component). 

I think this is correct for this ticket.

**Comment by jkeck** [comment]
👌

**Comment by jkeck** [comment]
Closed by #169

**Comment by anarchivist** [comment]
OK, going back and looking at #179, I think this was wrong, but I'll break out the changes into a new ticket.
