### ISSUE TITLE
Collections page (a.k.a. collection-level search)

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#139]
The collections page is a search scoped to collection-level results only.

**Acceptance criteria:**

*  ~ Implement ~ #190 Broken out in a different ticket
*  ~An indication of the total of number of collections (i.e. results) appears ~ Popped out to #200
* [x] Pagination, page size, and sort controls appear
* [x] A standard set of facets appears (what exists when work is started on the ticket is started is fine)
* [x] A shared, application-wide header appears at the top 
     * [x] Indication that the "Collections" page is active should be clear
* [x] A brief route for the page (e.g. `/collections`, not a long search-based URL)
* [x] Breadcrumb link leads back to the application home page 

**Out of scope for this ticket**

* "Online content" indicator #148 
* Per-collection thumbnails (probably out of scope for the MVP)
* Visual representation of collection/component levels #193 
* Full view vs. abbreviated view selection
* Date histogram facet #141 

**Mockup** 

![collections-page-search-markedup](https://cloud.githubusercontent.com/assets/73732/25076379/3831dc42-22d5-11e7-9dd9-8337d2583b27.jpg)

**Comment by mejackreed** [comment]
Checkout https://github.com/sul-dlss/arclight/issues/149#issuecomment-296672629 for info regarding how to do a limited search to a collection

**Comment by mejackreed** [comment]
I opted instead to do collection limiting by the "Name" and not the id
