### ISSUE TITLE
Expanded date range facet with larger histogram

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#141]
This is a refinement of #8.

**Acceptance criteria**

* The date facet should appear in a prominent location _outside_ the existing facet sidebar and _above_ the result set 
* Histogram should show major divisions (by century OR by decade?) 
* The histogram [or the whole facet?] should be collapsible
* Needs text entry*

**Mockup**

![collections-page-search-markedup](https://cloud.githubusercontent.com/assets/73732/25077234/c820ebd4-22dc-11e7-9c55-b0a99b28616f.jpg)

**Comment by gordonleacock** [comment]
We did our own sidebar facet for the last project I worked on. It allowed you to see the number of matches on hover and to zoom in on any time period by clicking.
![screen shot 2017-04-20 at 3 13 03 pm](https://cloud.githubusercontent.com/assets/12927191/25248420/31d2fff2-25dc-11e7-82aa-db30c6ce0b4c.png)
![screen shot 2017-04-20 at 3 13 34 pm](https://cloud.githubusercontent.com/assets/12927191/25248426/354254d0-25dc-11e7-8d3a-ba86d0ea782a.png)

**Comment by gordonleacock** [comment]
That that's no helpful, please ignore ;-)

**Comment by mejackreed** [comment]
Question for @ggeisler ... How should a user "submit" their new range query?

**Comment by ggeisler** [comment]
@mejackreed Maybe we add a "Update date range" button (`btn-sm` to minimize vertical space)? Ideally toggling the button state to `disabled` when there is no update from the current query reflected in the range? @jvine ?

![arclight-mockups-end-user-ui__results_-_all](https://cloud.githubusercontent.com/assets/101482/26123690/a36333f4-3a30-11e7-9989-e41cf23d11c5.png)

**Comment by mejackreed** [comment]
👍  great will do!
