### ISSUE TITLE
Facet and refine search results by geographic location

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#143]
Users should be able to facet by geographic location (i.e. place names)

**Acceptance criteria**

* Indexing a finding aid known to have geographic names (marked up in EAD as `<geogname/>`) should be have appropriate values indexed into a facet field (e.g. `a0011.xml`)
* The facet group title should appear as "Geographic Location"
* Selecting a value for the Geographic Location facet should filter results to that match that value
* Fixture data requirement: must contain `<geognames/>`

**Comment by drh-stanford** [comment]
@anarchivist Our alphaomegaalpha.xml currently doesn't have a `geogname` in it.
