### ISSUE TITLE
Collection detail page - overview with full detail and navigation

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#144]
This is a refinement of #138. This adds multiple headings for groupings of additional data, and a navigator to the left-hand side of the page. 

**Acceptance criteria**

* Display of the following section headings, with the corresponding data:
    * Summary (see #138)
    * Access and Use (see #138)
    * Biographical / Historical (same as "Background" in mockup) - data from `<bioghist/>`
    * Scope and Arrangement 
         * Scope and content: `<scopecontent/>`
         * Arrangement: `<arrangement/>`
    * Related
         * Related material: `<relatedmaterial/>`
         * Separated material `<separatedmaterial/>`
         * Other Finding Aids `<otherfindaid/>`
         * Alternative Form Available `<altformavail/>`
         * Location of originals `<originalsloc/>`
    * Indexed terms
         * Specific children of `<controlaccess/>`: `<corpname/>`, `<famname/>`, `<function/>`, `<genreform/>`, `<geogname/>`, `<occupation/>`, `<persname/>`, `<subject/>`, and `<title/>`
    * Administrative Information
         * Acquisition information: `<acqinfo/>`
         * Appraisal information: `<appraisal/>`
         * Custodial history: `<custodhist/>`
         * Processing Information: `<processinfo/>`
* A navigation bar in a lefthand sidebar, with entries for each heading that link to those headings.
* The navigation aid should also exhibit "scrollspy" behavior, highlighting the currently active section.

**Mockups**

![collection-detail-overview-markedup](https://cloud.githubusercontent.com/assets/73732/25079069/f5d3d6f2-22ed-11e7-9bba-857267a6409f.jpg)

![collection-detail-overview-no-inventory-markedup](https://cloud.githubusercontent.com/assets/73732/25079071/fbaf007e-22ed-11e7-95a5-698d6d9ea7cf.jpg)

**Comment by jkeck** [comment]
@anarchivist it looks like our current fixtures does not have any `arrangement` data.  I'm not 100% sure what kind of data should go in there if you want to shoot me something I can add it in my PR so I can write tests that the data shows up.

**Comment by jkeck** [comment]
Also, it appears that none of the data for the `Related` section is available in our current fixture.
`<relatedmaterial/>`, `<separatedmaterial/>`, `<otherfindaid/>`, `<altformavail/>` and `<originalsloc/>` are all not present.

**Comment by anarchivist** [comment]
Working on that now…

**Comment by jkeck** [comment]
Just continuing through the spec, it looks like we're missing `<appraisal/>`, `<custodhist/>`, and `<processinfo/>` from the Administrative Information section.

Haven't followed up on the Indexed terms because I think we want to build off of the work in #169.

**Comment by anarchivist** [comment]
@jkeck see #175
