### ISSUE TITLE
Collection detail page - contents/inventory section MVP

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#149]
The MVP for the contents section of the collections detail page displays information about the immediate children of the top-level description. 

**Acceptance criteria**

* A navigation bar that allows a user to switch between the summary section and the contents section
* If there are children of the top-level description:
    * There should be an entry for each child of the top-level description, which displays the following information:
        * Title and/or dates as one string, and component identifier (`<unitid/>`) if available, linking to the appropriate component-level show page
        * The first ~175 characters of the scope and content note (if available)
    * The entry in the nav bar should read "Contents"
    * The children should be displayed in order as they appear in the source data -- **CAN BE BROKEN INTO A NEW TICKET**
* If there are no children of the top-level description:
    * The entry in the nav bar should read "No content inventory" and not be clickable

**Out of Scope for this ticket**

* A label indicating the number of children of that child, with the appropriate level if identifiable (#189)

**Mockups**

![collection-detail-contents](https://cloud.githubusercontent.com/assets/73732/25080031/5ffcc360-22f6-11e7-8f7d-96c472d39a79.jpg)

![arclight-mockups-mvp](https://cloud.githubusercontent.com/assets/73732/25080045/7b846070-22f6-11e7-93c8-1d952e0f5ac4.jpg)

**Comment by mejackreed** [comment]
Writing some notes here. I think a successful query might be:

`fq":["component_level_isim:1", "ead_ssi:aoa271"]`

**Comment by jkeck** [comment]
We may want to pull having customized metadata displays for the content inventory into a separate ticket.
