### ISSUE TITLE
Add additional EAD data to fixtures

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/arclight#151]
Whether it be via new data in the existing fixture or additional fixtures. Fixture data will drive features.

- [x] ArchiveSpace as authoritative source for new fixtures
- [x] Manually edited XML to add new data to existing features (feel free to compare to an ArchivesSpace export)
- [x] EAD Schema validation #152
- [ ] Rake task to format cleanly #153

**Comment by mejackreed** [comment]
Just a note on ASpace. There seems to be problems w/ round tripping EAD's in ASpace. In doesn't always equal out, so we may need to hand edit some stuff.

**Comment by anarchivist** [comment]
From the 18 April standup:

* New fixtures should be authored by creating the data in ArchivesSpace, and then exported to EAD
* Adding data to existing fixtures should be done manually, to avoid the roundtripping problem identified by @mejackreed 
    * Can use ArchivesSpace export as guidance as well if unsure how to express, but changes should still be made manually
* We should be validating fixtures against the EAD schema (see #152)

**Comment by anarchivist** [comment]
More daos and more creator tags

**Comment by anarchivist** [comment]
Closing for now...
