### ISSUE TITLE
Target Blacklight master so we're using Bootstrap 4

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/arclight#154]
(and don't have to upgrade later on down the road)

* Look into what it would take to get a gem like the date slider to work from master.

**Comment by mejackreed** [comment]
List of items to tackle for this to work in blacklight_range_limit:

 - [ ] Figure out a better way to set `solr_field` here: https://github.com/projectblacklight/blacklight_range_limit/blob/master/app/views/blacklight_range_limit/_range_limit_panel.html.erb#L2
 - [ ] include Bootstrap tether . Bootstrap-gem recommends installing via rails-assets but this can be weird when in a gem/engine. Potentially could just be added in generator?
 - [ ] Bootstrap tooltip code needs upgrading (using some BS2 patterns)
