### ISSUE TITLE
Update README with instructions on how to use the template installer

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/arclight#174]
Additional work may be required for an actual template installer to work for real users (e.g. copying solr configurations over, etc.).  Hopefully thinking through what the documentation for the template installer might look like we can identify any changes we might need to make for an easy install via the template.

**Comment by mejackreed** [comment]
We might want to add something like this to the install process?

```ruby
def solr_config
  directory '../../../../solr', 'solr'
end

```
https://github.com/geoblacklight/geoblacklight/blob/master/lib/generators/geoblacklight/install_generator.rb#L48-L50

**Comment by drh-stanford** [comment]
Sorry, I put that documentation into `arclight-demo` -- that's probably the wrong place for it now. See https://github.com/sul-dlss/arclight-demo/blob/master/README.md#regenerating-the-application
We can use that information for a start and migrate it over here.

**Comment by drh-stanford** [comment]
We have a couple pages on the Wiki now that describe the process.

* https://github.com/sul-dlss/arclight/wiki/Creating,-installing,-and-running-your-ArcLight-application has the template based creation
* https://github.com/sul-dlss/arclight/wiki/Upgrading-your-ArcLight-application has the instructions for running `rails g arclight:update`

Given that information, can we close this ticket? Or does the template.rb need further work?

**Comment by drh-stanford** [comment]
@jkeck @mejackreed @anarchivist I'm closing this ticket as we've added documentation to the Wiki for it. Please reopen if we need anything further.

**Comment by anarchivist** [comment]
Thanks @drh-stanford !
