### ISSUE TITLE
Add indexed terms to collection show page

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/arclight#179]
Broken out of #144 

* Indexed terms
  * Specific children of `<controlaccess/>`: `<corpname/>`, `<famname/>`, `<function/>`, `<genreform/>`, `<geogname/>`, `<occupation/>`, `<persname/>`, `<subject/>`, and `<title/>`.

![collection-detail-overview-no-inventory-markedup](https://cloud.githubusercontent.com/assets/73732/25079071/fbaf007e-22ed-11e7-95a5-698d6d9ea7cf.jpg)

**Comment by jkeck** [comment]
@anarchivist can the same be said about the xpath for getting subjects for the collection show display as in https://github.com/sul-dlss/arclight/issues/11#issuecomment-295937041? (with the exception that we want more subject elements for this ticket)

**Comment by anarchivist** [comment]
The collection-level show page should only show subjects (`<subject/>`, `<function/>`, etc.) expressed at that level only for now.

**Comment by anarchivist** [comment]
Ooof, I think this a conflict with what I said on the comment on #11. I'll look again in the morning.

**Comment by anarchivist** [comment]
Per #184, only collection-level controlled access terms should show up here.
