### ISSUE TITLE
Component show pages and search results are inconsistent regarding commas

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/arclight#180]
Are the fixture data wrong? Or do we want to handle this case of trailing punctuation in the titles (which happens in the search results as well, for example)?

## Screenshot of a component show page

<img width="820" alt="screen shot 2017-04-20 at 3 42 07 pm" src="https://cloud.githubusercontent.com/assets/1861171/25255553/173b2094-25e0-11e7-9188-04e4fc52f777.png">

## Screen shot of a search result

![screen shot 2017-04-27 at 1 21 55 pm](https://cloud.githubusercontent.com/assets/73732/25502693/8be036ac-2b4c-11e7-8b9d-e35b443c4b2f.png)

## The XML fixture data

<img width="842" alt="screen shot 2017-04-20 at 3 44 30 pm" src="https://cloud.githubusercontent.com/assets/1861171/25255586/456ac74e-25e0-11e7-9bc6-974fd1443cb3.png">

**Comment by anarchivist** [comment]
I don't know if the fixture data is wrong, but I'm wondering if this is because the fixture is based on an EAD with pre-existing commas was imported to ArchivesSpace. EAD adds commas on export, I believe.

I need to give the decision more thought, but for now I'll fix the fixture data.

**Comment by anarchivist** [comment]
Per standup on 4/27 - the component show page should use the same strategy as used for the search results.
