### ISSUE TITLE
Enable text search

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/arclight#183]
A few ways to do this, does anyone have any thoughts on which way we should go on it?

**Comment by jkeck** [comment]
Could you enumerate the options, as you see them for doing this?

We definitely should have some sort of base search behavior (right now your can search text that displays in the search results and get no results).

**Comment by mejackreed** [comment]
- modify the `qf` from solrconfig to search explicit arclight fields
- use copyfield to pop searchable things into `text`
- from arclight specifically pass in these params (rather than config in solr)

**Comment by jkeck** [comment]
Dumping everything to `text` and never having to think about it when adding additional fields would be nice.  I'm guessing we may end up needing that anyway as a catch-all field at the bottom of our relevancy ranking.

The only concern I would have would be the potential index bloat, but I don't really have any evidence to base that on (and disk space is cheap).

**Comment by mejackreed** [comment]
So maybe like: 

```xml
 <copyField source="*im" dest="text"/>
```

Not sure what the right suffix is here

**Comment by jkeck** [comment]
Yeah, this is something the suffix thing came up the other day when I was pairing w/ @drh-stanford.

I think in a lot of cases where we've overridden part of the SolrEad defined terminology to be displayable we've only been adding `:displayable`, but through an initial check it seems like that removed the indexed field.  That should be easy enough to change though, and then I think that suffix should work.
