### ISSUE TITLE
Collection detail page overview: link terms/names to new faceted searches 

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#188]
On the collection detail page, the following items should be linked to new faceted searches. The location of these elements should stay the same.

* ~Creator (i.e. children of `<origination/>` - `<persname/>`, `<corpname/>`, `<famname/>`): link to a new Names facet query~
* ~Subjects (i.e. `<subject/>`, `<function/>`, `<genreform/>`, `<occupation/>`): link to a new Subject facet query~
* ~Names (i.e. `<corpname/>`, `<persname/>`, `<famname/>` and `<name/>` but only when children of `<controlaccess/>`): link to a new Names facet query~
* ~Places (i.e. `<geogname/>` but only when children of `<controlaccess/>`): link to a new Places facet query~

**EDIT**: #202 implements a link to an "all subjects" facet. #207 addresses the need to link specific terms/names back to the appropriate kind of facet query.

**Mockup**

![arclight-mockups-mvp2](https://cloud.githubusercontent.com/assets/73732/25345031/b3183304-28c8-11e7-9e19-439c94f1b444.jpg)

**Comment by jkeck** [comment]
The grouping of the different subjects to be linked to different facets will require a bit of custom rendering work that may take some additional thought.  Per discussion at standup, we'll take a first pass by simply linking subjects to a single subjects facet, and break out a ticket about linking subjects to separate facets.

cc: @anarchivist

**Comment by anarchivist** [comment]
Does @gordonleacock's PR #202 address the first part? If so, should we just treat this ticket to do that breakout?

**Comment by anarchivist** [comment]
Closed; see #207 for remaining needs.
