### ISSUE TITLE
Display the number of children of a given collection or component

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#189]
Display a label indicating the number of children of a given collection or component ~with the appropriate level if identifiable~.

**Acceptance criteria**

* If a collection-level record has 10 child components identified as series, the label should read "10 children"
* If a series-level record has 5 children whose level is not specified, the label should read "5 children"
* The label word "children" should be configurable

**Mockups** 

![arclight-mockups-mvp](https://cloud.githubusercontent.com/assets/73732/25349924/47740d02-28d8-11e7-876c-c0266740ed5e.jpg)

![arclight-mockups-mvp](https://cloud.githubusercontent.com/assets/73732/25350088/d47e2b92-28d8-11e7-9169-297fed472384.jpg)

**Comment by drh-stanford** [comment]
We can count the number of children for a given node at index time. That can be done via XPath's `count()` function -- e.g., `count(c)`. I can try that out.

As I understand this ticket, this is only for the collection detail page, right? The tougher problem here is that if the counts need to reflect the number of children that match a given search.

**Comment by jkeck** [comment]
I _think_ we can get away with just getting the count of the immediate child `c` elements.

In my initial experiment, adding `count(c)`, `count(/c)`, and `count(//c)` didn't get me the number I would have expected (e.g. I always received either `0`, or `1`) but didn't dig any deeper into it.

**Comment by anarchivist** [comment]
For this ticket, we're only looking for the count of the immediate child `<c/>` elements.

**Comment by drh-stanford** [comment]
Ok, so the problem with the XPath expression is that OM *always* adds a `//` to the beginning of the expression. So `path: 'count(c)'` is actually executed as `//count(c)` which is an invalid expression. I didn't look into how we could override this, but I can.

If `c` always has an `id` parameter, then we can do something like this where we grab all the id values for the components, then count them up:

```
--- a/lib/arclight/custom_document.rb
+++ b/lib/arclight/custom_document.rb
@@ -19,6 +19,7 @@ module Arclight
       t.occupation(path: 'archdesc/controlaccess/occupation/text()', index_as: %i[displayable facetable])
       t.places(path: 'archdesc/controlaccess/geogname/text()', index_as: %i[displayable facetable symbol])
       t.otherfindaid(path: 'archdesc/otherfindaid/p', index_as: %i[displayable])
+      t.component_ids(path: 'c/@id', index_as: %i[displayable])
 
       # overrides of solr_ead to get different `index_as` properties
       t.extent(path: 'archdesc/did/physdesc/extent', index_as: %i[displayable])
@@ -43,6 +44,7 @@ module Arclight
     def to_solr(solr_doc = {})
       super
       solr_doc['id'] = eadid.first.strip.tr('.', '-')
+      solr_doc['component_count_i'] = component_ids.length
       arclight_field_definitions.each do |field|
         Solrizer.insert_field(solr_doc, field[:name], field[:value], field[:index_as])
       end
```

Unfortunately, the EAD 2002 spec says that the `id` parameter is not required, but maybe it is in practice? See http://eadiva.com/2/c/
