### ISSUE TITLE
Add a cert for arclight-demo.projectblacklight.org

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#191]

**Comment by mejackreed** [comment]
Confirmed cert now added

**Comment by jkeck** [comment]
Well, almost.  The app is certed, but apparently forcing https on the load balancer side isn't super simple.

If we get https://github.com/sul-dlss/arclight-demo/pull/13 merged then the app will force https all the time.

**Comment by anarchivist** [comment]
Is this a DevOps concern and/or should this be reopened?

**Comment by jkeck** [comment]
I think this is the preferred solution.  We (now) do the same exact thing for the Blacklight demo site, so I think we're 👌.

**Comment by mejackreed** [comment]
:shipit:
