### ISSUE TITLE
Optimize solrconfig

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/arclight#197]
Currently the solrconfig does not necessarily reflect what is being indexed. This could be optimized further.

**Comment by anarchivist** [comment]
Related: need an audit of the indexed fields

**Comment by drh-stanford** [comment]
I went through the current `solrconfig.xml` and `schema.xml` files and they both are much better than before. @mejackreed can you be more explicit about what optimizations you'd like to see? we're using dynamic fields almost exclusively.

**Comment by mejackreed** [comment]
Yeah this was from 3 weeks ago so I think we are in a much better shape now. With the great work in #342 and #338 I'm not sure we need this anymore?

**Comment by drh-stanford** [comment]
Ok, I'll close it and we can revisit if needed.
