### ISSUE TITLE
Ingest EAD2002 following minimum DACS requirements

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#2]
Ingest a minimal subset of EAD2002 based on the [DACS single-level minimum requirements](http://www2.archivists.org/standards/DACS/part_I/chapter_1).

> A single-level description with the minimum number of DACS elements includes:
>
> * Reference Code Element (2.1)
> * Name and Location of Repository Element (2.2)
> * Title Element (2.3)
> * Date Element (2.4)
> * Extent Element (2.5)
> * Name of Creator(s) Element (2.6) (if known)
> * Scope and Content Element (3.1)
> * Conditions Governing Access Element (4.1)
> * Languages and Scripts of the Material Element (4.5)

**Comment by drh-stanford** [comment]
do we have some existing examples (i.e., fixtures) for EAD content?

**Comment by anarchivist** [comment]
@drh-stanford 💬 

> do we have some existing examples (i.e., fixtures) for EAD content?

Yes, will populate a Google Drive folder and link it

**Comment by anarchivist** [comment]
Sample data folder: https://drive.google.com/open?id=0B20rJmC1X-AmZU9HTzJiMWpFdlk

**Comment by drh-stanford** [comment]
These are the EAD elements mappings to the minimum requirements:

* [ ] Reference Code Element (2.1) -- `*/did/unitid`
* [ ] Name and Location of Repository Element (2.2) -- "repository" -- `archdesc/did/repository`
* [ ] Title Element (2.3) -- `*/did/unittitle`
* [ ] Date Element (2.4) --  `*/did/unitdate`
* [ ] Extent Element (2.5) -- `*/did/physdesc`
* [ ] Name of Creator(s) Element (2.6) (if known) -- `*/did/origination/(persname|corpname|...)`
* [ ] Scope and Content Element (3.1) -- `*/did/scopecontent` -- minus `head`
* [ ] Conditions Governing Access Element (4.1) -- `*/accessrestrict` -- minus `head`
* [ ] Languages and Scripts of the Material Element (4.5) -- `*/did/langmaterial/language`

**Comment by drh-stanford** [comment]
Also, we need to figure out a consistent way to uniquely identify the Solr documents `id` at all `level` values from collection to item.

**Comment by drh-stanford** [comment]
Blocked by adding minimal EAD test fixture.

**Comment by anarchivist** [comment]
@drh-stanford see aa40fb1
