### ISSUE TITLE
Merge "Administrative Information" into "Background"?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/arclight#205]
@anarchivist On the Collection Overview page we're currently showing seven categories for the overview information. During the design phase we actually spent quite a bit of time thinking about the categories and trying to consolidate them to just six. Admittedly this is fairly subtle, but I do think six versus seven is significant here, especially given "Administrative Information" wraps to two lines. Six single line labels are arguably much easier to comprehend at a glance than seven, especially when one of those wraps.

What do you think about moving the Administrative Information sections to Background? I believe Background will often only contain a single element and the Administrative Information elements, while more about the acquisition and processing history than the biographical history, do feel like they fit as part of the general background of the collection. 

(I think I've also seen the Admin Info elements under Access and Use and Scope and Arrangement on other sites. Also, in the long-run, we of course hope to enable the implementor to customize these sections so our decision wouldn't be fixed forever.)

Here's a comparison of how the collection navigation sidebar looks now and if we move Admin Info to Background:

### Current
![alpha_omega_alpha_archives__1894-1992_-_blacklight](https://cloud.githubusercontent.com/assets/101482/25461728/784154bc-2a9f-11e7-87a7-97e20cace403.png)

### Proposed
![alpha_omega_alpha_archives__1894-1992_-_blacklight 2](https://cloud.githubusercontent.com/assets/101482/25461722/73f671bc-2a9f-11e7-9cea-51b4b2b1aca5.png)

**Comment by anarchivist** [comment]
Thanks. I'm giving this some thought, but my first set of reactions is as follows.

* "Background" is somewhat confusing as a label. I get the sense that OAC grabs the first matching `<p/>` tag in `<bioghist/>` for their "Background" section.
* Maybe the `<bioghist/>` could be moved into something like "Scope and Arrangement" with a new label? 
* The "Administrative Information" section could probably be given a pithier title. Maybe "Collection History" following your Front Matter Decomposition spreadsheet?

I'd like to get a temperature check on this from stakeholders.

**Comment by ggeisler** [comment]
So maybe move  `<bioghist/>` to "Scope and Arrangement" and then rename "Administrative Information" to "Collection History", leaving us with six headings? That would work for me, though I wonder if `<bioghist/>` as part of "Scope and Arrangement" might not be loved by other stakeholders.

If we did that, I'd suggest putting the "Collection History" heading where "Background" currently is, rather than at the end of the list.

Based on what I saw surveying existing finding aids online, I'm guessing that archivists will lean towards having more (specific) headings but I'm looking at it from a UX perspective and believe that keeping the headings more limited will make the page easier to scan and more inviting to users.

**Comment by anarchivist** [comment]
> So maybe move <bioghist/> to "Scope and Arrangement" and then rename "Administrative Information" to "Collection History", leaving us with six headings? That would work for me, though I wonder if <bioghist/> as part of "Scope and Arrangement" might not be loved by other stakeholders.

Yeah, that's one aspect I'm wondering about. I had an informal conversation with someone yesterday, and the sense I got was that the biographical/historical note conceptually made more sense grouping it with the scope and contents note than grouping it with things like custodial history, acquisition info, etc. 

> Based on what I saw surveying existing finding aids online, I'm guessing that archivists will lean towards having more (specific) headings but I'm looking at it from a UX perspective and believe that keeping the headings more limited will make the page easier to scan and more inviting to users.

I'm in agreement here. I'm less concerned about specific headings, honestly, and just making sure that the groupings of notes fields make sense together, hence my comment above.

I'll follow up about this further and create new tickets as needed.

**Comment by anarchivist** [comment]
Feedback on Slack:

@helrond 💬 

> so to make a somewhat radical suggestion - bioghist, scope/content and most of what’s in administrative information all seem like “Background” to me

@eckardm 💬 

> I guess I'm thinking if you have to group something together, biography/history and scope and contents makes sense as a grouping

@helrond 💬 

> [re: administrative information] they’re part of the “background” of the collection in the sense that they’re archival interventions that shape what the user will encounter
> ...
> i’m not sure there’s anything in an arrangement note that can’t be represented more effectively in some other way.

To that end, my inclination is as follows: 

* Group bioghist, scopecontent, and what's in Administrative Information now into Background
* Remove arrangement (just suppress it from view) to demonstrate configuration

**Comment by anarchivist** [comment]
Added new ticket as #215. I'm closing this for now otherwise.
