### ISSUE TITLE
Link terms/names to new faceted searches based on the appropriate facet field

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#207]
Created from #188.

On the collection detail page, the following items should be linked to new faceted searches. The location of these elements should stay the same.

* Creator (i.e. children of `<origination/>` - `<persname/>`, `<corpname/>`, `<famname/>`): link to a new Names facet query
* Subjects (i.e. `<subject/>`, `<function/>`, `<genreform/>`, `<occupation/>`): link to a new Subject facet query
* Names (i.e. `<corpname/>`, `<persname/>`, `<famname/>` and `<name/>` but only when children of `<controlaccess/>`): link to a new Name facet query
* Places (i.e. `<geogname/>` but only when children of `<controlaccess/>`): link to a new Place facet query

**Mockup**

![arclight-mockups-mvp2](https://cloud.githubusercontent.com/assets/73732/25345031/b3183304-28c8-11e7-9e19-439c94f1b444.jpg)

**Comment by drh-stanford** [comment]
closed by PR #424
