### ISSUE TITLE
Relocate bookmark/request checkboxes in search result items

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/arclight#223]
As discussed at standup, we need to resolve the issue of where to place the bookmark/request checkboxes in relation to the collection/item identifiers and where relevant, the "online content" badge. Currently things like like this:

![-_blacklight_search_results](https://cloud.githubusercontent.com/assets/101482/25540489/157facea-2c00-11e7-8e46-e43deeac3e86.png)

I suggest that we:

* Leave the "online content" badge in the same row at the result item title, as I think it currently is
* Show the collection ID/item hierarchy left-aligned after the parent repository name
* Move the bookmark and request checkboxes to the `.text-right` div in the `.al-document-title-bar` div (I'd also reduce the `.text-right` div to 3-col and increase its sibling div to 9-col)

So the arrangement would look roughly like this (the mockup below includes reducing the font-size in the  `.al-document-title-bar` div and other styling updates, which I can do in a separate PR):

![collection__the_italian_or_the_confessional_of_the_black_penitents___typescript_-_blacklight_search_results 2](https://cloud.githubusercontent.com/assets/101482/25540727/f4b0fd2e-2c00-11e7-987c-950b434e4aa8.png)

**Comment by ggeisler** [comment]
This change is also appropriate for the component detail page (e.g, p. 10 of the MVP mockups) but ideally the `al-document-title-bar` of the Collection show page _would not_ inherit this change, but would remain the way it currently is.

**Comment by anarchivist** [comment]
This sounds good to me. Per post-standup discussion in Slack with @jkeck, I've moved this into the Ready column.
