### ISSUE TITLE
Display repository-specific information on top of search results faceted by repository

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#225]
Prerequisites: #222, #226  

**Acceptance criteria** 

* Assumptions
    * At least one repository configured according to data structure laid out in #222 
    * At least one finding aid associated with a configured repository (see #226)
* On a search result page faceted by repository:
    * Display the existing facet info/clear info
    * If the repository is configured using the #222 data structure,
         * display the appropriate "card" display containing repository info
    * Otherwise, don't display anything additional

**Mockup**

![arclight-mockups-mvp](https://cloud.githubusercontent.com/assets/73732/25550518/90e376d6-2c2e-11e7-9512-a5f4863500fa.jpg)

**Comment by drh-stanford** [comment]
Just to be clear -- any search that _includes_ a facet on Repository should have this repository card feature. So, you could be faceting on repository and have a text search, or faceting on subject and repository, and you'd see the repo card. Is that correct?

**Comment by anarchivist** [comment]
Yes, that's correct.
