### ISSUE TITLE
During indexing, specify a configured repository with which to associate indexed collections/components

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#226]
**Acceptance criteria**

* When indexing, I should be able to _optionally_ specify an identifier/slug for a configured repository (see #222) 
* Indexed documents should have information assigned from the configured repository information rather than data from the source to be indexed
* If I try to index with an identifier/slug that doesn't match a preconfigured one, throw an error

**Comment by drh-stanford** [comment]
@anarchivist where specifically is the repository **identifier/slug** in the EAD data? It looks like it could be in a few places based on http://eadiva.com/2/repository/. Right now, for our `repository_ssm` Solr field, we're using the name from `corpname` or `name` within the `<repository>` section.

My understanding of this ticket is that during indexing time if we have a match for the EAD's repository data (specifically the "slug"), then we use our matching data from `repositories.yml` in #222.

**Comment by anarchivist** [comment]
@drh-stanford The data is not there consistently, even for Stanford data - but where we'd look is `/ead/eadheader/eadid/@mainagencycode`. When I wrote this ticket I was imagining be able to specify it at indexing time something like this: 

```bash
$ bundle exec rake arclight:index REPOSITORY_ID=example_slug FILE=example.xml
```

**Comment by drh-stanford** [comment]
Ok. If we use the `@mainagencycode` as the slug, then I'm worried about your 3rd bullet, as your `config/repositories.yml` would need to have information about that slug or it'll error out. That may be a problem as you keep adding EADs.

But that (using `@mainagencycode`) would be my preferred approach as the slug data would be encoded in the EAD itself rather than in an run-time variable that you have to specify per file.

**Comment by anarchivist** [comment]
@drh-stanford and I just chatted about this:

* We should not use `@mainagencycode` since we can't guarantee it'll be there, and this behavior effectively overrides what's in the EAD.
* We should be able to specify a slug at the Rake task's runtime using an environment variable. 
* (Perhaps a separate ticket): We should be able to index a directory of files as a rake task, and pass the environment variable for the repository slug. This is a simplified and less tightly coupled approach than what NYU's `ead_indexer` does.
