### ISSUE TITLE
Collection detail page - inventory/contents - expanded view

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#227]
Builds on #149. 

This expands the inventory view on the collection detail page to allow for displaying nested components.

**Acceptance criteria**

* For each child component, add a "view more" link
* Clicking the "view more" link expands to display all child components at the next immediate level
* Each child component should display:
    * Title and date in one line, which link to the show page for that component
    * Creator if present
    * Extent if present
    * Scope and contents note if present 
    * Access restrictions if present
    * Use restrictions if present
    * Basic container information if present (#20)
    * a "View More" link to expand to show that component's children - the default state should not show the expanded view

**Out of scope**

* Nested box/folder displays as included in the mockup
* Sortable components lists

**Mockups** 

![before](https://cloud.githubusercontent.com/assets/73732/25572635/ec86b470-2df1-11e7-82b7-58114e32cf10.jpg)

![after](https://cloud.githubusercontent.com/assets/73732/25572638/f366d5cc-2df1-11e7-9a97-674d1f5fc182.jpg)

**Comment by jkeck** [comment]
Note: we need to add the addl. metadata described above to the current top-level component partials.
