### ISSUE TITLE
Add level hierarchy to document title bar

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/arclight#229]
Pulled out from #223 for more discussion.

The mockups split the enumerated container designation and the label between the breadcrumb and the document title bar.  This data is not split out in the EAD (at least not in the data that we've seen so far) and will take further consideration with regard to how we would generate the necessary data to drive this display.

![screenshot](https://cloud.githubusercontent.com/assets/101482/25540727/f4b0fd2e-2c00-11e7-987c-950b434e4aa8.png)

**Comment by anarchivist** [comment]
I think this is a non issue - I think the breadcrumbs that have been added to to search results fix this.
