### ISSUE TITLE
Display link/description for digital objects

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#237]
Prerequisite: (PR: #253)

**Acceptance criteria**

Display links, and when available, descriptions of digital objects at either the collection and component level show views. For this ticket, the understanding is that a `<dao/>` tag must have an `href` attribute containing a valid URI, and may occur within the top-level `<archdesc/>` tag or individual `<c/>` components.

* In the left sidebar add a new section titled "Online" when there is a `<dao/>` at the appropriate level.
* In this section, for each `<dao/>` at a given level:
    * Display either the `<dao/>`'s `title` attribute OR its `<daodesc/>` 
    * Add a ink to the URI identified in the `href` link with the text "Open"

**Comment by jkeck** [comment]
![screen shot 2017-05-01 at 11 34 54 am](https://cloud.githubusercontent.com/assets/96776/25589647/3ebea16a-2e62-11e7-8e03-df2242400cdf.png)
