### ISSUE TITLE
Add README for setup and indexing test data for testers

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#239]
We need a set of instructions for users to follow to index their own local test data. 

**Acceptance criteria** 

* A user should be able to
   * spin up a new demo app
   * index EAD exported from ArchivesSpace 
   * load the demo app and see the data
   * know how to contact us if they have questions or run into errors

**Comment by mejackreed** [comment]
I think this is now done (except for the contact us part). @anarchivist I'll let you decide how the contact part should work

Please see:

 - https://github.com/sul-dlss/arclight/wiki/Creating,-installing,-and-running-your-ArcLight-application
 - https://github.com/sul-dlss/arclight/wiki/Indexing-EADs-in-ArcLight

**Comment by anarchivist** [comment]
Cool. I just added a link to the wiki home page to the Google Group - I think that takes care of the contact requirement.
