### ISSUE TITLE
Create a request from a component show page

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#243]
This should be added in the same context as #234.

**Acceptance criteria**

On a component show page for a component with container information:

* [x] Display a button to request that component in the sidebar #284
* [x] Clicking a request button should pop up a partially filled Google Form #294 

**Now out of scope for sprint 5**

* Clicking the request button should pop up a request form, containing all applicable information #285 
* Submitting a request form should send the request somewhere #286 

**Mockup**

<img width="182" alt="screen shot 2017-04-30 at 11 15 58 pm" src="https://cloud.githubusercontent.com/assets/73732/25573546/478fc2fe-2dfb-11e7-949d-bf663033d31f.png">

**Comment by mejackreed** [comment]
Question for @ggeisler ... is the "request" feature tied somehow to the "Before you visit" section? or are these independent?

**Comment by ggeisler** [comment]
@mejackreed I think that if a component is requestable, it will have the `Request containers` button in the `Before you visit` section, as well as the `Request` button in the context section in the main area of the component detail page, as on p. 11 of the MVP mockups.

**Comment by anarchivist** [comment]
Marking as closed because of the completion of #284 and #294.
