### ISSUE TITLE
Autocomplete/typeahead

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#244]
**Acceptance criteria**

When a user begins typing query terms into to a search box anywhere in the application:

* the user sees recommendations for their queries below the search box
* the user can select the recommendations either with the keyboard or with the mouse

**Out of scope**

* Field-specific search 
* Type-specific contextual clues (e.g., exclude the "person" labels)

**Mockup**

![arclight-mockups-end-user-ui](https://cloud.githubusercontent.com/assets/73732/26080122/ff8cbdce-3979-11e7-8922-1bbaf8195328.jpg)

**Comment by anarchivist** [comment]
To discuss: what fields should we included in autocomplete? Titles? Facets? etc.

**Comment by jkeck** [comment]
Okay, so starting the discussion on this.  We're already configured to use the autocomplete (as that's the default behavior).

So all we really need to do is to configure solr to populate the suggest field appropriately.  This will be in the solr schema that is managed by the application, so ultimately this will be customizable downstream.  Setting sane out-of-the box behavior to demonstrate the ability is most likely the best course of action.

One option would be to do something as simple as copy all the indexed fields using `*i` and `*im`, which is what we're currently doing for the catch-all text search field.

Alternatively, we can be more explicit about the fields that we're indexing into the suggester to only include titles and facets.

That list would most likely be something along the lines of:
- `title_ssm`
- `collection_sim`
- `names_ssim`
- `repository_sim`
- `places_ssim`
- `access_subjects_ssim`

**Comment by anarchivist** [comment]
I'm not super picky about the specific strategy, because I'm not sure about the nuances of each. However, I'll note that the list of fields that @jkeck describes follows what I'm roughly thinking for #334.

**Comment by jkeck** [comment]
Okay, I'm thinking I'll go w/ that for now.  Folks can feel free to comment on the PR.
