### ISSUE TITLE
Highlight hits in search results

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#245]
**Acceptance criteria**

When I search for a term and there are matches:

* I should see the terms highlighted in each search result, no matter where they appear 
* If the field does not normally display or is excerpted in the search results, show me adequate context for the term.
     * Presumption: We're not showing fielded highlighting results for this ticket; we probably are dumping all text into a single field for highlighting.

**Comment by mejackreed** [comment]
@anarchivist When reviewing this ticket, I'm interpreting that highlighting should be turned on in any search result. Per page 8 of the MVP mockups, highlights are showing up on a "show page" for a result. 

This implementation is much different than what was originally implemented in #146 and potentially in conflict with the intent of the mockups for "search within". I understood it a different way and thus implemented it in the way in which I thought was best consistent with Blacklight.

A few things we need to decide on:

  - Should "search within" continue to behave in its current state (easy) or should we try to make it behave in the way the mockups intended (hard). I offer that the mockup version is hard as it seems to conflict with the Blacklight model of "how things work".
 - Once we know the answer to the previous question, how should we proceed with hit highlighting?

cc @jvine @ggeisler 
Page 8 for reference:

![screen shot 2017-05-18 at 1 29 27 pm](https://cloud.githubusercontent.com/assets/1656824/26215841/d0c89582-3bcf-11e7-80dc-c6926c7ba7fb.png)

**Comment by anarchivist** [comment]
@mejackreed 

>  When reviewing this ticket, I'm interpreting that highlighting should be turned on in any search result. 

Yes, that is correct. 

> This implementation is much different than what was originally implemented in #146 and potentially in conflict with the intent of the mockups for "search within". I understood it a different way and thus implemented it in the way in which I thought was best consistent with Blacklight.

I understand, and to be clear, the mockup was only supposed to demonstrate the example of highlighting - not the context in which it shows up for search within. 

> Should "search within" continue to behave in its current state (easy) or should we try to make it behave in the way the mockups intended (hard). I offer that the mockup version is hard as it seems to conflict with the Blacklight model of "how things work".

My inclination is that we should keep it in its current state, given the amount of time left in the work cycle. I'd be curious about @ggeisler and @jvine's feedback here, but I think this is a tradeoff we need to make.

> Once we know the answer to the previous question, how should we proceed with hit highlighting?

What else do you feel like you need here? This may be a case where we need some design, since we don't have a mockup that reflects this implementation.

**Comment by ggeisler** [comment]
I think we need @jvine's input here, since she focused a lot more on the search results related mockups than I did. I thought the hit highlighting was intended just for the search within on the collection detail page, as in the mockups, but I could be wrong. To me, it makes more sense for the collection detail page than general search results (where the result items are sorted by relevance).

If we want hit highlighting to apply to all search results we'd have to figure out how much we show for each component that contains a hit (e.g, if a given component has a long scope note and has hits strewn throughout that long note). Currently we show very limited metadata for each result hit, which helps keep the results list manageable to scan. I worry that introducing hit highlighting for all results could produce very long, less scannable search results lists. Of course, we could design a solution to attempt to minimize that.

**Comment by jvine** [comment]
I looked at this last night but was a bit confused about what the current state is. I'm okay with keeping highlighting only in the search-within results, if that's what's being proposed.

But the highlighting _was_ meant to be in all search results. Highlights are finicky to mockup when things are in flux, so I had illustrated it in the within-collection search only. I thought there was a comment to this effect in the document, my oversight if not. 

The mockups do include a snippet in the general search results that is meant to include at least one instance of the search terms. 

![screen shot 2017-05-19 at 9 31 17 am](https://cloud.githubusercontent.com/assets/6945691/26257562/f3a3321e-3c75-11e7-9529-1f8b99c053ef.png)

But if we are not showing a snippet in the general search results, then I'm not sure it makes sense to do hit highlighting there - they will only highlight that some results don't have an obvious match.

**Comment by anarchivist** [comment]
@jvine 💬 

> I looked at this last night but was a bit confused about what the current state is. I'm okay with keeping highlighting only in the search-within results, if that's what's being proposed.

This ticket is proposing adding highlighting to the context of general search results, and my intention was to follow the snippet pattern in the mockups. We have not yet implemented the snippet itself in the search results, but my understanding is that this ticket would add the snippet through the work on highlighting. 

@ggeisler 💬 

> If we want hit highlighting to apply to all search results we'd have to figure out how much we show for each component that contains a hit (e.g, if a given component has a long scope note and has hits strewn throughout that long note).

I think [highlighting is configurable](https://cwiki.apache.org/confluence/display/solr/Highlighting) on the Solr side - we can identify the number of snippets to return and their length (in terms of characters).

**Comment by anarchivist** [comment]
* Perhaps show first (or only one) snippet per component? 
* Do we know how many hit counts we get in highlighting responses?

**Comment by drh-stanford** [comment]
I've done some digging into the implementation of this with @jkeck. The vanilla Blacklight support for highlighting will likely not work for us and we'll need some custom code to implement this.

The default Solr behavior is to return the first snippet only. We can get the hit count for highlighting at a performance cost (using the `hl.snippets=9999`). I don't have a sense of how much the performance would slow down -- it depends on what the hit counts are.

On the technical side, we discovered that highlighting only works on fields that are both **stored** and indexed -- see the solr config files here for the changes needed -- https://github.com/sul-dlss/arclight/compare/245-highlighting

**Comment by drh-stanford** [comment]
@ggeisler @anarchivist are these screenshots what we have in mind for the highlighting on the general search results? Note that in some cases when the hit is in the title, for example, it doesn't try to highlight it in the actual title display -- i.e., the hits always show up in the little "highlighting area". It's technically more difficult afaik to do highlighting inline.

## Query: student life

![screen shot 2017-05-25 at 2 21 16 pm](https://cloud.githubusercontent.com/assets/1861171/26471193/a547cc9e-4155-11e7-9e3f-3ccd645d892b.png)

## Query: national library of medicine. history of medicine division

![screen shot 2017-05-25 at 2 20 41 pm](https://cloud.githubusercontent.com/assets/1861171/26471195/a7e399a6-4155-11e7-9b19-a693af6a75a4.png)

## Query: library

![screen shot 2017-05-25 at 2 16 26 pm](https://cloud.githubusercontent.com/assets/1861171/26471199/a9c40abc-4155-11e7-8638-81ca7b695e70.png)

**Comment by ggeisler** [comment]
Looks okay to me. If @jvine has time to take a quick look, her input might be more useful.

**Comment by jvine** [comment]
👍  Looks fine, except for finding "history" when you searched "library". ;-)
