### ISSUE TITLE
Poor indexing performance from slow XPath expressions

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/arclight#250]
We found that OM via the `solr_ead` code adds a `//` prefix to nearly all of our xpaths. This would likely explain the poor performance for large-ish files. We may be able to rewrite the xpath expressions to be absolute -- e.g., starting with `/` so that OM doesn't add the `//` prefix.

See https://github.com/sul-dlss/arclight/issues/189

**Comment by billdueber** [comment]
I submitted a pull request for this upstream -- see https://github.com/awead/solr_ead/pull/20

Ref: #472 #267

**Comment by gordonleacock** [comment]
I think that's part of what Bill's code does.
