### ISSUE TITLE
Responsive layout is wonky

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#266]
See attached screenshots.

* Hamburger menu at top overlaps ArcLight logo in a portrait layout
* Bookmark checkbox looks screwy

![screen shot 2017-05-03 at 9 52 22 pm](https://cloud.githubusercontent.com/assets/73732/25690978/7db9bd9c-304b-11e7-8169-21bbd5e1f534.png)

![screen shot 2017-05-03 at 9 54 55 pm](https://cloud.githubusercontent.com/assets/73732/25690986/86e473e4-304b-11e7-8e59-94af85964973.png)

**Comment by mejackreed** [comment]
Part of this is a Blacklight core thing. Hopefully we can work on that upstream

![screen shot 2017-05-08 at 2 06 20 pm](https://cloud.githubusercontent.com/assets/1656824/25818127/90c94498-33f7-11e7-91e1-7b400f784a96.png)
