### ISSUE TITLE
Indexing performance is incredibly poor even on small-ish finding aids

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#267]
I was testing indexing some finding aids from the Bentley ([Google Drive folder](https://drive.google.com/open?id=0B3DqcSBOaZWWbmFDYlVyRnB2Q2c)), and even some relatively small finding aids index slowly. 

The finding aid in question is `umich-bhl-0728.xml`.

We ran into this before with finding aids from SPEC, too, and I'll confirm with a specific example. 

See #250 for one known issue.

**Comment by anarchivist** [comment]
I'll add that Bentley's `umich-bhl-0234.xml` is roughly 3x larger, and indexes quickly.

**Comment by mejackreed** [comment]
It might be good to add some benchmarking of the problem here so that we can determine when performance changes.

**Comment by drh-stanford** [comment]
https://github.com/sul-dlss/arclight/pull/262 adds timings to each file indexed so collecting the benchmarking should be easier when that it merged. In the meantime if you prefix your rake task with `time bundle exec rake arclight:index...` you can get timings

**Comment by anarchivist** [comment]
Goals:

* Set up tooling for benchmarking at a more detailed level
* List of EAD files with timings and characteristics
* Identify ideal timings based size/characteristics
* Index larger EAD files for testing

**Comment by drh-stanford** [comment]
Here's what a profile looks like, and most are like this for the longer indexing times (this particular one is from `umich-bhl-2013066.xml`). At a high level, the indexing is taking most of its time inside OM when it's trying to parse the document and each component. There's an n x m problem here because it extracts the entire terminology from each component. It also applies the terminology using `//` as the xpath prefix so it's scanning all the nodes for all the components and all the terminologies. That's why we're seeing ~100k `xpath` calls. OM's xpath "mangler" is complicated and it's the biggest resource consumer. 

```
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name
  6.11    15.26     15.26   141954     0.11     0.43  OM::XML::TermXpathGenerator.generate_xpath_with_indexes
  4.27    25.92     10.66   158810     0.07     0.13  Nokogiri::XML::Searchable#extract_params
  3.98    35.86      9.94   304440     0.03     0.08  OM.destringify
  3.85    45.48      9.62   183572     0.05     0.10  OM::XML::Terminology#retrieve_term
  3.49    54.19      8.71   592816     0.01     1.09  Array#each
  2.95    61.55      7.36   136330     0.05     0.37  Solrizer::Suffix#to_s
  2.93    68.86      7.31     3556     2.06     2.15  Nokogiri::XML::Document.read_memory
  2.75    75.72      6.86    36430     0.19     2.29  OM::XML::TermValueOperators#term_values
  2.33    81.53      5.81   105590     0.06     0.39  Nokogiri::XML::Searchable#xpath
  2.15    86.90      5.37    85327     0.06     0.11  OpenStruct#new_ostruct_member!
  2.04    92.00      5.10   338073     0.02     0.04  Kernel#dup
  1.86    96.64      4.64   358592     0.01     0.02  Kernel#initialize_dup
  1.72   100.93      4.29    85340     0.05     0.17  OpenStruct#method_missing
  1.55   104.80      3.87    52795     0.07     0.08  Nokogiri::XML::XPathContext#evaluate
  1.45   108.43      3.63    65984     0.06     0.37  Sanitize::Config.merge
  1.42   111.97      3.54    56973     0.06     0.08  Sanitize::Config.can_dupe?
  1.41   115.49      3.52    65956     0.05     0.31  Sanitize#transform_node!
  1.35   118.85      3.36     9551     0.35     0.40  Nokogiri::XML::Node#native_write_to
  1.28   122.05      3.20   972576     0.00     0.00  Module#===
  1.12   124.85      2.80   170674     0.02     0.02  Kernel#define_singleton_method
  1.07   127.52      2.67    74982     0.04     0.05  Solrizer::Suffix#has_field?
  1.07   130.19      2.67    77603     0.03     6.49  Nokogiri::XML::NodeSet#each
  0.90   132.44      2.25   154012     0.01     0.23  Class#new
```

**Comment by drh-stanford** [comment]
Here are some file timings that show the indexing time depends on the number of components in the EAD

| File | realtime | size | # of components |
| --- | --- | --- | --- |
| m0198_from_ASpace.xml | 2 secs | 5k | 6 |
| alphaomegaalpha.xml | 10 secs | 31k | 35 |
| umich-bhl-0047.xml | 10 secs | 17k | 35 |
| umich-bhl-0234.xml | 65 secs | 91k | 253 |
| umich-bhl-0312.xml | 73 secs | 148k | 280 |
| umich-bhl-2013066.xml | 153 secs | 184k | 557 |

**Comment by drh-stanford** [comment]
I'm going to run some experiments with changing the `solr_ead` component indexing code to help figure out what's going on.

The test case will be `umich-bhl-0234.xml` that has the following profile:

```
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name
  6.42     3.83      3.83    66738     0.06     0.24  OM::XML::TermXpathGenerator.generate_xpath_with_indexes
  4.11     6.28      2.45   272072     0.01     0.58  Array#each
  4.06     8.70      2.42    88528     0.03     0.05  OM::XML::Terminology#retrieve_term
  4.04    11.11      2.41   145872     0.02     0.05  OM.destringify
  3.72    13.33      2.22    68438     0.03     0.07  Nokogiri::XML::Searchable#extract_params
  3.20    15.24      1.91    65387     0.03     0.21  Solrizer::Suffix#to_s
  2.62    16.80      1.56    40958     0.04     0.06  OpenStruct#new_ostruct_member!
  2.53    18.31      1.51    17695     0.09     1.19  OM::XML::TermValueOperators#term_values
  2.36    19.72      1.41    46006     0.03     0.21  Nokogiri::XML::Searchable#xpath
  1.98    20.90      1.18   152853     0.01     0.02  Kernel#dup
  1.83    21.99      1.09   162397     0.01     0.01  Kernel#initialize_dup
  1.59    22.94      0.95    40971     0.02     0.09  OpenStruct#method_missing
  1.39    23.77      0.83   438671     0.00     0.00  Module#===
  1.34    24.57      0.80    36162     0.02     0.03  Solrizer::Suffix#has_field?
  1.31    25.35      0.78    23003     0.03     0.04  Nokogiri::XML::XPathContext#evaluate
  1.26    26.10      0.75     1234     0.61     0.61  Nokogiri::XML::Document.read_memory
  1.24    26.84      0.74     1257     0.59    11.15  Kernel#require
  1.14    27.52      0.68    18631     0.04     0.04  Sanitize::Config.can_dupe?
  1.09    28.17      0.65    81936     0.01     0.01  Kernel#define_singleton_method
  1.01    28.77      0.60    63442     0.01     0.12  Class#new
```

**Comment by drh-stanford** [comment]
I've found so far that OM is slow, very slow at times, but may not be entirely unreasonable, unfortunately. I'd like to discuss what our expectations are indexing times. Fundamentally, if a EAD has 1,000 components and we're extracting like 50 terms for the Solr document, that's 50,000 xpath queries. I've found that the individual xpath queries are really fast but they add up.

Some of the never-return index failures is due to multiple date ranges for a component. We'll address that in a different ticket.

**Comment by anarchivist** [comment]
Some timings for Hoover finding aids:

| File | realtime | size | # of components |
| --- | --- | --- | --- |
| 2014C4.xml | 1.12 secs | 36K | 68 |
| 2016C32.xml | 0.61 secs | 59K | 38 |
| reg_178.xml | 31.15 secs | 511K | 2081 |

**Comment by drh-stanford** [comment]
| File | realtime | size | # of components |
| --- | --- | --- | --- |
| umich-bhl-014.xml | 76 secs | 79k | 279 |
| umich-bhl-0728.xml | 13 secs | 28k | 40 |
| umich-bhl-2014137.xml | 20 secs | 32k |  80 |
| umich-bhl-851981.xml | xxx | 1.2m | 4,341 |
| umich-bhl-9840.xml | xxx | 51k | 135 |

**Comment by drh-stanford** [comment]
Some items for discussion.

1. Is 30 minutes to index a single EAD acceptable for the MVP? What about an hour? The time depends on the number of components in the EAD -- it takes roughly a half-hour for 5k components (on a slow-ish laptop).

2. Doing performance tuning on OM, Solrizer, and/or solr_ead is not likely to yield dramatic results. It is slow, for a variety of reasons. OM in particular handles complex use cases and the code is complex and not well tuned. So, if we need more dramatic results, I think we can rewrite solr_ead to NOT use OM or Solrizer, but note that we still have to index N fields for M components and that gets large.

3. If we want to do incremental performance tuning, there's a few places to take a look.
  - Our use of Solrizer is surpisingly slow, so I would avoid calling `insert_field` or `set_field` and cache the Solr field name generation (which is slow and called a lot). We're doing this in deep loops. The problem, however, is that OM is using Solrizer in the `to_solr` calls so we'd have to PR OM.
  - Nokogiri::XML document proliferation. We create/parse a new document for every component. Instead we could just operate on the selected node and reuse the same document tree. As is, it's inefficient and about 10-15% of the CPU time. We have control over this option as it's all in solr_ead.
  - OM has (really) complicated xpath generation and logic to support all sorts of use cases that we don't need. So we could write a shim that mimics OM in `solr_ead` to simplify the xpath generation and execution. We're not using complex terminologies (in fact, they are all flat).
  - The actual xpath execution, regardless of using a `/` or `//` prefix, is fast (0.3 ms/call). The document tree is in memory and our EAD components are not that large. So, we probably wouldn't get much improvement fir we tweaked our xpath queries.

**Comment by drh-stanford** [comment]
Here are the timings with the multidate workaround and no profiling:

| File | realtime | size | # of components |
| --- | --- | --- | --- |
| umich-bhl-2016071.xml | 1 secs | 5k | 1 |
| m0198_from_ASpace.xml | 1 secs | 5k | 6 |
| alphaomegaalpha.xml | 1 secs | 31k | 35 |
| umich-bhl-0047.xml | 1 secs | 17k | 35 |
| umich-bhl-0728.xml | 1 secs | 28k | 40 |
| umich-bhl-2014137.xml | 1 secs | 32k |  80 |
| umich-bhl-9840.xml | 2 secs | 51k | 135 |
| umich-bhl-0234.xml | 5 secs | 91k | 253 |
| umich-bhl-014.xml | 5 secs | 79k | 279 |
| umich-bhl-0312.xml | 6 secs | 148k | 280 |
| umich-bhl-2013066.xml | 15 secs | 184k | 557 |
| umich-bhl-2012140.xml | 291 secs | 1.4m | 2,478 |
| umich-bhl-851981.xml | 485 secs | 1.2m | 4,341 |

**Comment by anarchivist** [comment]
Re: 1: I think 30 to 60 minutes is tolerable for the MVP but less than ideal. Documenting the relationship is probably sufficient. My biggest concern was identifying the source of inconsistency of indexing performance, which you pinned down to the date range issues.

The one blocker to this, as @jkeck notes, is indexing performance being a potential blocker to deploying the demo site. We should probably have a broader conversation about how to deal ith that. 

Re: 3, I think these are all good starting points for discussion, but I think we've mitigated my most serious concerns. I look forward to discussing this more.

**Comment by drh-stanford** [comment]
With the PRs, we're able to index ~500 components/min for EADs with 1000s of components. I'm going to close this ticket and we can reopen or create other tickets if we want to improve the performance further.
