### ISSUE TITLE
Component show page: repository/unitid/bookmark bar appears twice

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#270]
I think this might have been introduced by #265. 

![screen shot 2017-05-04 at 2 00 59 pm](https://cloud.githubusercontent.com/assets/73732/25724828/30d2bdee-30d2-11e7-9b71-0cc1a7e8964d.png)

**Comment by jkeck** [comment]
@anarchivist have you rebuilt your internal test app recently? I'm not seeing this behavior on a fresh rebuild on master.

**Comment by anarchivist** [comment]
That fixed it. Thanks!
