### ISSUE TITLE
Properly render components that contain unitdate without unittitle

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#273]
Per archival description practices, component levels should have a title (`<unittitle/>` in EAD), a date (`<unitdate/>`), or both. Currently, components with only `<unitdate/>`s are not displaying properly (see screenshots).

**Screenshots**

![screen shot 2017-05-04 at 10 01 54 am](https://cloud.githubusercontent.com/assets/73732/25726476/317b772a-30d9-11e7-818b-9f03b8cd8ac2.png)

![screen shot 2017-05-04 at 2 45 14 pm](https://cloud.githubusercontent.com/assets/73732/25726485/3f8883b2-30d9-11e7-9f6b-7b4445d1a0c1.png)

**Acceptance criteria**

* A component with a `<unittitle/>` and a `<unitdate/>` should be rendered as it is now
* A component with a `<unitdate/>` only should display the data within the `<unitdate/>`'s text node 
* This change should occur whenever a component title gets rendered (including breadcrumbs, if applicable)

**Sample data** 

* [umich-bhl-0312.xml](https://drive.google.com/open?id=0B3DqcSBOaZWWMEJqZTVTQ3ZXYlE)

**Comment by drh-stanford** [comment]
What should happen if there's neither a unittitle or a unitdate?

I've isolated the problem to here: https://github.com/sul-dlss/arclight/blob/master/app/presenters/arclight/index_presenter.rb#L7 as well as the show presenter.

**Comment by jkeck** [comment]
@drh-stanford yeah, that's [default Blacklight behavior](https://github.com/projectblacklight/blacklight/blob/master/app/presenters/blacklight/index_presenter.rb#L37).  It needs **something** to use as the title otherwise you wouldn't have a way to navigate to the record page.

**Comment by anarchivist** [comment]
If there's no title or date, than using the `id` is fine, but it should have at least one or the other. If their is, the data is suboptimal.
