### ISSUE TITLE
Display request buttons in components lists

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#287]
**Acceptance criteria**

In displays where lists of components appear:

* [x] Display a "Request" button for each component with containers
* [x] Clicking a request button should pop up a request form with the right info 

**Questions**

* Should this appear in collection's inventory view as well as the tabular component display (#231)?
* Is this expected to be achieved how do we best select multiple components for requests? Check boxes or something similar?

**Mockup**

![arclight-mockups-mvp](https://cloud.githubusercontent.com/assets/73732/25776845/e645a116-327e-11e7-81e5-a3d18feb8039.jpg)

**Comment by ggeisler** [comment]
@anarchivist I'd say the answer to this question:

> Should this appear in collection's inventory view as well as the tabular component display (#231)?

is Yes.

**Comment by ggeisler** [comment]
@anarchivist:

> Is this expected to be achieved how do we best select multiple components for requests? Check boxes or something similar?

I think our idea was if the user wanted to request multiple containers in a single request they would bookmark each desired component and then from their Bookmarks page (design TBD) they'd be able to select multiple bookmarked components and click a request button there to make a single request for all selected components. From the inventory or component detail page they'd only be able to request one component at a time.

We could reevaluate this if necessary, though enabling a single request for multiple components on the inventory/component detail pages will complicate the UI of those pages somewhat.

**Comment by mejackreed** [comment]
@ggeisler  @anarchivist when you say "In displays where lists of components appear". Does this include a search results page?

**Comment by mejackreed** [comment]
Looking at the mocks, I'm assuming yes

**Comment by ggeisler** [comment]
Yep.

**Comment by anarchivist** [comment]
I think that's right, but I was specifically talking about the hierarchy view (and not yet implemented  tabular view) here.
