### ISSUE TITLE
Enable bookmarked components to be requested from bookmarks list

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#288]
**Acceptance criteria**

Given a user has bookmarked one or more components and is viewing their bookmarks:

* [ ] Check to see which components have container info
* ~Allow user to create a request containing multiple components, populating data into a request form~
* [ ] Allow user to submit a new request for those components which have container info

**Comment by anarchivist** [comment]
Design is probably needed when dealing with multiple selected items.

**Comment by ggeisler** [comment]
After discussion with @jvine, we recommend **not** enabling selection of multiple containers with one request, at least at this stage where the app doesn't know when different components are actually part of the same requestable container (e.g., "Box-folder 18 : 1" and "Box-folder 18 : 2").

For now we'd suggest just providing a Request button at each component that is a container, and the user would request them individually. This doesn't seem ideal in practice, but until we have a better handle on how ArcLight would be integrated with request apps this seems like the most feasible approach.

So the Bookmarks page might look like this, where the first item is a collection and thus not requestable, but the next three items are and thus get a "Request" button next to the Bookmark checkbox. 

![bookmarks_-_blacklight](https://cloud.githubusercontent.com/assets/101482/26515581/e90d547c-4230-11e7-8b9a-8816371d47fc.png)

Ideally, it would be nice to change the state of the Request button to show that it has been requested ("Requested") but unless we get feedback from the request app that the request has been received, I'm not sure we can reliably do that.

**Comment by jkeck** [comment]
@anarchivist this is what the Bookmarks page currently looks like when you've bookmarked requestable content.

<img width="1133" alt="bookmarks" src="https://cloud.githubusercontent.com/assets/96776/26698560/4fde8a2e-46cb-11e7-871a-2f4cfee7dd50.png">

Are there additional acceptance criteria that we need to meet to close out this ticket?

**Comment by anarchivist** [comment]
Nope - I think this looks good. I'll just need to take a spin for acceptance testing. Thanks!

**Comment by anarchivist** [comment]
OK, looks good. Thanks! Ready for merging.
