### ISSUE TITLE
Document or provide way to check indexer's expectations for EAD

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#293]
Suggested by @cazzerson. We should give people guidelines about the expectations that ArcLight or the indexer puts on EAD finding aids.

Examples:

* All components must have an `id` attribute
* All components must have at least `<unittitle/>` or `<unitdate/>`

Potential forms:

* documentation
* Schematron file
* Helpful warnings or errors during indexing

**Comment by mejackreed** [comment]
Is it acceptable to raise an error on indexing with a helpful error message?

**Comment by anarchivist** [comment]
Yes, that would be acceptable.

**Comment by mejackreed** [comment]
Some more documentation added: https://github.com/sul-dlss/arclight/wiki/Indexing-EAD-in-ArcLight/_compare/b01984298bcd6a5bb48deec2b88b607d00890aa5...40bb48f1975ec8dac65d7b27197bed61d938ef0c

**Comment by drh-stanford** [comment]
this is merged now
