### ISSUE TITLE
Clicking a request button should pop up a partially filled Google Form

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#294]
Broken out of #243 and adapted from #285. 

**Acceptance criteria**

* When a user clicks a "request container(s)" button, a Google form should appear in a new tab/window.
* The request form should contain the following fields:
    * [ ]  _Not editable/prefilled:_ Collection title
    * [ ]  ~~  _Not editable/prefilled:_ Collection creator ~~ putting this off as it isn't indexed
    * [ ]  _Not editable/prefilled:_ Collection ID 
    * [ ] ~~ _Not editable/prefilled:_ Titles/dates for full hierarchy to the requested component (e.g. the breadcrumb) ~~ unclear what this means
    * [ ]  _Not editable/prefilled:_ Component title and/or dates
    * [ ]  _Not editable/prefileld:_ Container information (e.g. box/folder, and barcode if included) 
    * [ ]  _Editable:_ Visit date
    * [ ]  _Editable:_ Comment field
    * [ ]  _Editable:_ Name
    * [ ]  _Editable:_ Email address

**Comment by anarchivist** [comment]
Can you tell me why you're unclear about the hierarchy information?

**Comment by mejackreed** [comment]
Yeah sure. I'm not really sure what that means. Is that the full headings for the entire hierarchy? How are those supposed to be delimited? If the container has a unique identifier, what is the use case of providing this text based hierarchy?

**Comment by anarchivist** [comment]
Yes, this is basically the breadcrumb display without links.

There are cases where some collections may have multiple boxes with the same number. For example, Series I may have a box 8; series III may also have a different box 8.

**Comment by mejackreed** [comment]
Closing as I think the intent of this was closed by #307. I'm not sure about the details being needed without this as an actual use. Currently this is configurable.
