### ISSUE TITLE
View and navigate collections and components in search results

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#3]
Individual search results should include 

* Repository 
* Collection identifier (+ component identifier if exist)
* Title (collection title for collections, component title for components)
* Collection [title] (for components)
* Creator
* Date
* Extent
* Scope and Content 
* Access restrictions
* Languages and/or scripts

Ref: req 1.26

See #2 for ingestion details.

**Comment by anarchivist** [comment]
Rough mockup. Exclude what is described by #4 
![results1](https://cloud.githubusercontent.com/assets/73732/24984856/1176983c-1fa5-11e7-80f3-7c05a926a88a.png)

**Comment by drh-stanford** [comment]
Some things are not displayable like scopecontent and accessrestrict, and level (which is facetable but not displayable?). We need to revisit that.

**Comment by drh-stanford** [comment]
We have a PR #129 ready for review.

Note that Collection identifier (+ component identifier if exist) is not displayed but is in the title hyperlinks.
