### ISSUE TITLE
Context display: partial hierarchy - sibling display

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#300]
Broken out of #240. 

**Acceptance criteria**

Assuming #299:

* [x] Display 0-2 immediate sibling components of the current component following a similar pattern as #227 if available
* [x] Display 0-1 immediate sibling component of the current component's immediate parent

**Mockups**

![arclight-mockups-mvp](https://cloud.githubusercontent.com/assets/73732/25829739/1c8f8c3e-340d-11e7-8834-e7e97dc051f2.jpg)

**Comment by mejackreed** [comment]
@anarchivist for the sibling display, i see "display 0-2" siblings. Can you explain that a bit more. Should we show the preceding and following (if they exist) for example:

```
# if have surrounding siblings
Proceeding
Current
Following

# if first item
Current
Following 1
Following 2

# if last item
Proceeding 1
Proceeding 2
Current
```
