### ISSUE TITLE
Index collection creator(s) for all components

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#310]
Broken out of #294 and #285.

**Acceptance criteria**

* A component should have the creator information for its collection indexed into a new field.

**Comment by mejackreed** [comment]
I'm a little bit 👎  on this. Without a hard understanding of real world request specifications, it feels like adding additional indexing elements for theoretical uses is less than ideal. I guess my biggest concern is it feels like we would be adding cruft to the application/indexing for potentially unused data.

**Comment by anarchivist** [comment]
I think beyond requests, it would probably be useful to include the collection creator in the collection card displayed by #240/#298.

**Comment by jkeck** [comment]
@anarchivist what would the expected behavior for the `Creator` facet be?  Should it include the count of all the components (as well as include them in the search results when faceting), or is the collection Creator at the component level more for display purposes?

**Comment by anarchivist** [comment]
I would presume that the collection creator at the component level is primarily for display purposes at this point.

**Comment by anarchivist** [comment]
Here are some contexts in which the collection creator should display for a component:

* As a part of collection level info on the component page #298 
* In search results for components (with a field label like "Collection creator")
