### ISSUE TITLE
Indexing is stripping out two numerals following "c" 

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#313]
From Slack:

@anarchivist 💬  

> something i noticed with the Stanford video collection that’s weird: the `id` for the collection is `sc1031`, but for the components its `sc31-whatever`

@jkeck 💬 

> @anarchivist I've been a bit baffled by some of the ids as well.  For instance, in the AlphaOmegaAlpha collection, we have this component:
>
> See https://arclight-
demo.projectblacklight.org/catalog/aoa271aspace_843e8f9f22bac872d0802d6fffbb04 & https://github.com/sul-dlss/arclight-demo/blob/master/data/ead/nlm/alphaomegaalpha.xml#L255
>
>The ID of which you would think would be the collection id concatenated with the component id.  However; if you look at the component id, it's slightly different than the document id (plus the collection id).
>
> aspace_843e8f9f22bac872d0802d6fffbb04 vs.
> aspace_843e8f9f22bac69872d0802d6fffbb04

I *think* this  may be fixed by @drh-stanford's PR awead/solr_ead#15, but I haven't tested it.

**Comment by jkeck** [comment]
👏

**Comment by drh-stanford** [comment]
My PR should fix this issue. We can test it on the next solr_ead release.

**Comment by jkeck** [comment]
[SolrEad 0.7.5](https://github.com/awead/solr_ead/releases/tag/v0.7.5) has been released.

**Comment by anarchivist** [comment]
Yep, it's fixed! 🚀
