### ISSUE TITLE
Consistent display of unittitle/unitdate throughout the app

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#319]
Suggested by @drh-stanford in #305.

The combination of `<unittitle/>` and `<unitdate/>` should be presented consistently throughout the app - component/collection titles, breadcrumbs, etc.

* If there's a `<unittitle/>` with `<unitdate/>`: Join the two with a comma and a space, ensuring no double commas (per #180)
* If there's a `<unittitle/>`, but no `<unitdate/>`: Whatever the `<unittitle/>` is, with no trailing comma
* If there's a `<unittitle/>`, with `<unitdate>n.d.</unitdate>`: Whatever the `<unittitle/>` is + `, n.d.`
* If there's no `<unittitle/>`, with `<unitdate>n.d.</unitdate>`: `n.d.`
* If there's no `<unittitle/>` or `<unitdate/>`: issue a warning and use the component `id`?

*Edit*

* If the `<unitdate/>` has a `type` attribute set to `bulk`, prefix that date with `bulk`

Per @drh-stanford's suggestion we may want to approach this as normalization at index time.

**Comment by drh-stanford** [comment]
**Example of trailing comma in breadcrumb**

![screen shot 2017-05-12 at 10 30 48 am](https://cloud.githubusercontent.com/assets/1861171/26010133/962ebd9e-3700-11e7-8157-c946998cf7ba.png)

**Comment by drh-stanford** [comment]
@anarchivist do we want to do data cleanup for date ranges that are confusing (at least confusing to me), like "YYYY, n.d."? Some examples:

![screen shot 2017-05-12 at 10 52 20 am](https://cloud.githubusercontent.com/assets/1861171/26010270/1fb8ea4e-3701-11e7-978c-f4cc0ba1744a.png)
![screen shot 2017-05-12 at 10 52 10 am](https://cloud.githubusercontent.com/assets/1861171/26010274/2180423c-3701-11e7-994f-e4f698fbd4d4.png)

The indexing code handles the year facet by using `(1913..1960)` and `1904` respectively. I'm not sure what the `n.d.` is trying to specify in these cases...

**Comment by anarchivist** [comment]
These dates should be presented in views as they are now. They are intended to represent cases where component may have a known date or date ranges for some material, but other materials within the same component may be undated.

**Comment by drh-stanford** [comment]
Here's another example of the "YYYY, n.d." type data. My understanding is that we should leave these as-is:

![screen shot 2017-05-12 at 11 07 50 am](https://cloud.githubusercontent.com/assets/1861171/26010827/57c00466-3703-11e7-9c22-24ec2126272c.png)

@anarchivist What about date ranges that are overlapped, like this one in `umich-bhl-0234`? I read that to mean simply "1956-1994". Is that correct in this example? If so, should we be removing the "1968-1993" part?

![screen shot 2017-05-12 at 11 08 14 am](https://cloud.githubusercontent.com/assets/1861171/26010828/59c08eb6-3703-11e7-9002-ccc85d6c841f.png)

**Comment by anarchivist** [comment]
For the Abdeen Jabara papers, these are technically two types of dates (as indicated by the `type` attribute): inclusive dates and bulk dates (see [DACS 2.4.10](http://www2.archivists.org/standards/DACS/part_I/chapter_2/4_date)). For cases like this, we should probably render the dates as so:

> Abdeen Jabara papers, 1956-1994, bulk 1968-1993

The Alpha Omega Alpha was modified and thus isn't a good example, so should just  follow the way it's rendered now. There may be an argument to modifying the fixture to follow a pattern as laid out by [DACS 2.4.11](http://www2.archivists.org/standards/DACS/part_I/chapter_2/4_date).

**Comment by drh-stanford** [comment]
@anarchivist should the Collection facet use "Title, Date" or just "Title" as it is now?

**Comment by drh-stanford** [comment]
here's an example my modifications for the breadcrumbs with the dates:

![screen shot 2017-05-12 at 3 28 40 pm](https://cloud.githubusercontent.com/assets/1861171/26019081/b7f1a078-3727-11e7-93da-d16f7f5bf3fd.png)

**Comment by anarchivist** [comment]
@drh-stanford I'm a little torn on this - I think there's a strong argument to use title/date for the collection title facet for the sake of consistency, but I'm also worried about the length of some of these titles. 

@ggeisler - what do you think?

**Comment by ggeisler** [comment]
Yeah, I could go either way with this as well. I do worry about the length when we include dates in the title for the collection facet.  But collection titles can be long without the date, so relatively speaking, maybe it's not a big deal?

Maybe for sake of consistency, we go with including the date in the facet titles for now and we revisit later when we have more data and see if we think it would be a better UX if we don't include the dates?

**Comment by anarchivist** [comment]
That sounds good - so yes, let's include the dates in the collection title facet as well.

**Comment by drh-stanford** [comment]
Here's an example of the comma in the title isn't cleaned up properly.

<img width="817" alt="screen shot 2017-05-16 at 10 53 27 am" src="https://cloud.githubusercontent.com/assets/1861171/26120595/216d2148-3a26-11e7-8266-0f4f21d0e9e3.png">

**Comment by anarchivist** [comment]
@drh-stanford I think that example is fine to stay as is.

**Comment by drh-stanford** [comment]
@anarchivist should we also be following 2.4.12 (using "circa") and 2.4.16 (using "undated")?

**Comment by anarchivist** [comment]
@drh-stanford Yes, but I'm guessing that those should be present in the text node of the `<unitdate/>`.

**Comment by drh-stanford** [comment]
Yes, they are but they aren't normalized into the "circa" and "undated" terms. So, we have things like "c.1980", "c. 1980", "circa 1980", etc. I put the normalization code into #323 and we can remove it easily enough. There are a alot of cases for `unitdate` in general, but I think I've codified them in #323.

**Comment by anarchivist** [comment]
OK - yeah, per my comment on @jkeck's review of #323, I would keep the "circa", "undated", "n.d." etc. out of scope for the normalization code for now.
