### ISSUE TITLE
Demo site: some components have been indexed twice

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#320]
Because of the resolution for #313, some components are showing up twice in the index. I'm not opinionated on the strategy, but maybe we could clear out the index on deploy?

![screen shot 2017-05-12 at 1 56 21 pm](https://cloud.githubusercontent.com/assets/73732/26010548/4f9df208-371b-11e7-83f6-90f0c76bdfbb.png)

**Comment by mejackreed** [comment]
I think this may have happened b/c of the solr_ead id tweak.

**Comment by jkeck** [comment]
Ah, the SolrEAD indexing code deletes existing IDs, but had no way of knowing to delete the old IDs.  I'll work w/ DevOps to get the index cleared out.

**Comment by drh-stanford** [comment]
We can change the `demo:seed` task to nuke all the documents in the index first.

**Comment by mejackreed** [comment]
Closed with the merge of https://github.com/sul-dlss/arclight-demo/pull/26

<img width="992" alt="screen shot 2017-05-16 at 12 30 15 pm" src="https://cloud.githubusercontent.com/assets/1656824/26117150/851b87fe-3a33-11e7-825a-7064de992cb2.png">
