### ISSUE TITLE
Component detail page/collection context: link to collection detail page

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#326]
**Acceptance criteria**

Given a component detail page, link to the collection's show view from the collection title that displays in the collection context section.

**Screenshot**

![screen shot 2017-05-15 at 11 37 23 am](https://cloud.githubusercontent.com/assets/73732/26073266/30fac67e-3963-11e7-882c-fd680907f338.png)

**Comment by mejackreed** [comment]
This was attempted in #353. Yet i'm concerned that providing a link to something here that we already are including in the page (we are already going and fetching part of the collection show page and injecting it here) is replicating functionality and changing how a user interacts with a common element pattern. This pattern in the application "a heading with a link -> should link to a page"

So the concerning part of this ticket here is:
> ... that displays in the collection context section

I would suggest here that when a user sees a heading link, that should "take them to that page".. thoughts? Or am I misunderstanding that part of the ticket?

**Comment by anarchivist** [comment]
I'm not sure why that part is concerning - as far as I can tell this follows the same pattern. This just makes the heading containing the collection title a link to the collection detail page.

**Comment by mejackreed** [comment]
So I think maybe we are saying the same thing then. Sorry if I misunderstood.

**Comment by anarchivist** [comment]
No problem! 👍
