### ISSUE TITLE
Repositories: display the actual count of collections for that repository

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#331]
**Acceptance criteria**

On the repositories page, for each repository:

* Display the actual count of collections for each repository

**Screenshot**

![screen shot 2017-05-15 at 4 58 42 pm](https://cloud.githubusercontent.com/assets/73732/26084303/0627352c-3990-11e7-8e6c-b8719f36d269.png)

**Comment by drh-stanford** [comment]
@anarchivist should the sort order for the repository list be by the collection count? right now, they show up in order that they are in `repositories.yml`

**Comment by anarchivist** [comment]
No, I think retaining the existing order is fine for this.

**Comment by drh-stanford** [comment]
also, fyi i noticed that the 'Learn more' button doesn't do anything right now.

**Comment by drh-stanford** [comment]
Here's an example of the page with the 3 conditions present -- 0, 1, and n collections.

![screen shot 2017-05-19 at 3 03 36 pm](https://cloud.githubusercontent.com/assets/1861171/26268511/5fd5e250-3ca4-11e7-8ea9-518083555897.png)

**Comment by ggeisler** [comment]
@drh-stanford The "Learn more" button is intended to go to a more descriptive repository page (sort of a show page for a repository). This page is in our End-User-UI mockups but not part of the MVP work. 

We could change the label to "See all" and link it to the search results faceted by that repository for now. That way the link does something somewhat useful, and we can change it back to match the original intention whenever we get to creating repository show pages. @anarchivist?

**Comment by anarchivist** [comment]
@ggeisler That sounds good to me for now. Thanks!
