### ISSUE TITLE
Accordion: "Online" section when online access is not available

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#332]
**Acceptance criteria**

For a given collection or component without digital objects: 

* Display an "Online" header in the accordion that is not expandable
* Change the label to read "Online (no online content)" 

**Mockup**

![screen shot 2017-05-15 at 5 16 01 pm](https://cloud.githubusercontent.com/assets/73732/26084615/447d58b8-3992-11e7-8946-c101f2542097.png)

**Comment by drh-stanford** [comment]
What is the behavior for a Collection that has online content in its components, but not for itself? Should it look like this?

![screen shot 2017-05-24 at 4 43 58 pm](https://cloud.githubusercontent.com/assets/1861171/26430143/378d835c-40a0-11e7-849e-2204436e3c60.png)

**Comment by ggeisler** [comment]
I think we should discuss this with @anarchivist. I think this ticket relates pretty closely to #277 and I'm not sure we have a final plan for that ticket yet. I'm concerned that the sidebar Online section makes less sense if we implement the core idea of #277, which is to add a third tab after Contents to represent online content.

**Comment by anarchivist** [comment]
Yeah, I'm wondering that as well. Let's discuss tomorrow.

**Comment by drh-stanford** [comment]
Ok, that's fine. I'll put this into design needed for now.

**Comment by ggeisler** [comment]
@anarchivist: @jvine and I discussed and we're thinking the Online section of the sidebar is not necessary if we implement the new "Online Content" tab as discussed in #277. 

We think the new tab basically makes the sidebar section unnecessary and keeping the sidebar section poses potential problems for long lists, etc., plus we've already heard feedback about it contributing to making the page feel busy. So maybe just get rid of it?

**Comment by anarchivist** [comment]
That sounds fine. Do you want to close this ticket and create a new one for adding the online content tab and getting rid of this sidebar block, or should I?

**Comment by ggeisler** [comment]
You can do it, since you're more on top of all the tickets. Note, though, the the new online content tab should be part of #277, I think? It's kind of confusing because the design we ended up with for #277 doesn't involve the viewer that is in the ticket title, but I think that is the solution we ended up with for that ticket. 

So maybe no new ticket is needed, but an edit to the title of #277?

**Comment by anarchivist** [comment]
I'm going to close this ticket and #277, just to make it clear. Thanks!

**Comment by anarchivist** [comment]
Added #416.
