### ISSUE TITLE
Online access facet

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#333]
Closes #13. 

**Acceptance criteria**

* Add a facet that filters to collections or components that have digital objects associated with them directly.
* The facet value should be "Online access".

**Discussion**

This facet in the mockups was originally intended to also specify whether a collection/component had restrictions. We're not sure if we can get that information precisely now. How should we move forward on this?

**Mockup**

![screen shot 2017-05-15 at 5 23 50 pm](https://cloud.githubusercontent.com/assets/73732/26084751/7199aeea-3993-11e7-854f-c1f94d96df08.png)

**Comment by ggeisler** [comment]
What are the values related to "access" we can reliably get? 

Is it just "online"?

**Comment by anarchivist** [comment]
@ggeisler At this point, we'd be constructing the value "Online" or "Online access" by the presence of `<dao/>` tags (the same behavior that drives the "online content" labels at the collection level).

**Comment by ggeisler** [comment]
I understand that. I was asking whether there are values relating to access other than "online" that we can reliably get.

**Comment by anarchivist** [comment]
Per discussion on 5/17 standup:

* Ideally, I'd like this to be a generalized access facet.
* However, we don't have consistent enough data for this to be doable. Most access restrictions are longer textual notes. (We could revisit this in the future, though.)
* I'm not opinionated about the UI implementation - it could be a checkbox rather than a facet as we have laid out now.
