### ISSUE TITLE
Fielded search from application-wide search bar

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#334]
**Acceptance criteria**

In the application-wide search bar in the header:

* [ ] Provide a dropdown to select the field to search
* [ ] Allow for keyword search (this is the existing "All Fields" search but improved)
* [ ] Allow for names search
* [ ] Allow for places search
* [ ] Allow for title search (both collection and components)
* [ ] Allow for subject search

**Comment by drh-stanford** [comment]
@anarchivist should these be in addition to the "All fields" search we have now? What should a "keyword" search against? Is that the same as our "All fields" search we have now?

Also, what should be the default search in the dropdown?

**Comment by drh-stanford** [comment]
@anarchivist I looked at our "All fields" search and there's really not that many fields covered in it. For example, Scope and Content isn't included in the text search.

So, can you provide a list of fields you'd like the "All fields" search to have?

Here's my understanding of what the dropdown should look like:

![screen shot 2017-05-17 at 11 38 39 am](https://cloud.githubusercontent.com/assets/1861171/26170202/66bfd504-3af5-11e7-96d7-b686b67cea13.png)

**Comment by anarchivist** [comment]
Sorry - "Keyword" should be equivalent to "All fields."

I'll work on providing a list of fields for "All fields" as well.

**Comment by drh-stanford** [comment]
ok, let's break the list of fields for "All fields" out into a new ticket. I have PR #338 that does the field-based searches scoped based on the criteria above.

**Comment by anarchivist** [comment]
I've added #347 to cover the rest of the changes. I've written this up based on the Solr field names rather than the EAD elements.
