### ISSUE TITLE
Add container information to components displayed in collection detail's contents view

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#339]
Discussed on the 5/17 standup. @ggeisler was walking through some modifications he was trying out to the design of the collection detail page's contents view to help sort through some of the issues on #231. 

**Acceptance criteria**

On the collection detail page, within the contents view:

* For each component with container information, display the container information roughly in line with the title and the children label
* The container information should be derived from each of the component's `<container/>` elements, using its`type` attribute and text node concatenated
* On display, information about multiple containers should be concatenated using `, ` (a comma plus a space)

**Example data**

```xml
      <c02 id="aspace_ref2_9yo" level="file">
        <did>
          <unittitle>Abbott, John A. - Correspondence</unittitle>
          <unitid>A1333-101 </unitid>
          <unitdate type="inclusive">1962-1990</unitdate>
          <container id="aspace_1978840645357f4e698faa3502040b6b" label="Mixed Materials" type="box">1</container>
          <container id="aspace_db6b8ffe2af3efe6b892d91d94defd5c" parent="aspace_1978840645357f4e698faa3502040b6b" type="folder">1</container>
        </did>
```

should lead to: `box 1, folder 1`

```xml
          <c05 id="aspace_c0876ed8fe8caefacceb227d582b2e6c" level="file">
            <did>
              <unittitle>Production and promotion</unittitle>
              <unitdate normal="1961/1965" type="inclusive">1961-1965</unitdate>
              <container id="aspace_09054137103dba2e4f9c4bc2d6baef87" label="Box" type="box">1</container>
            </did>
          </c05>
```

Should lead to: `box 1`

**Comment by mejackreed** [comment]
Pending a PR from @ggeisler

**Comment by drh-stanford** [comment]
@ggeisler how do you want the container information shown inline with the title?

Here's what I'm doing right now -- using a dash after the title

![screen shot 2017-05-23 at 12 53 43 pm](https://cloud.githubusercontent.com/assets/1861171/26373580/e8973d90-3fb6-11e7-8f02-0bd441bfcc5e.png)

**Comment by ggeisler** [comment]
@drh-stanford Can we put the container info before the title, as in:

> Box 1, Folder 2: Statements of purpose, c.1902
> Box 1, Folder 3: Constitution - notes on drafting of constitution, c.1902-1903

A final decision might depend on how that looks and the results of #231, but I'd like to try that approach as a start.

**Comment by drh-stanford** [comment]
Ok. Here's what that looks like -- note that the hyperlink is only on the title, not the container:

![screen shot 2017-05-23 at 1 12 17 pm](https://cloud.githubusercontent.com/assets/1861171/26374303/a905bc1c-3fb9-11e7-8088-b54d9c412848.png)

**Comment by ggeisler** [comment]
Cool, let's go with this. I'll need to figure out a way to make the collection link more clear anyway, so I'll experiment with some styling improvements. But this gives me a good foundation to work on.

**Comment by drh-stanford** [comment]
Blacklight was using "to_sentence" to display our containers, so we're getting "Box 1 and Folder 1" rather than "Box 1, Folder 1". I just want to make sure that we want the latter for both the title and the component show page.

## Before

![screen shot 2017-05-23 at 1 45 20 pm](https://cloud.githubusercontent.com/assets/1861171/26376658/23ad874e-3fc2-11e7-9698-a888a40e2c01.png)

## After

![screen shot 2017-05-23 at 1 48 14 pm](https://cloud.githubusercontent.com/assets/1861171/26376667/28bb80c4-3fc2-11e7-862c-645740d7473c.png)

**Comment by ggeisler** [comment]
Yes, the screenshots are what we want.
