### ISSUE TITLE
Styling bug in masthead

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/arclight#345]
We are getting a bit of side-scroll due to this.

Chrome: `Version 58.0.3029.110 (64-bit)`

<img width="548" alt="header-bug" src="https://cloud.githubusercontent.com/assets/96776/26179469/c6c033ae-3b18-11e7-8db4-ec2d76d41f6b.png">

**Comment by ggeisler** [comment]
@jkeck Is this the homepage? And at what viewport size? I haven't been able to recreate, although I'm running a slightly older version of Chrome -- `Version 57.0.2987.133 (64-bit)` -- so am wondering if it is a browser-version thing.

**Comment by jkeck** [comment]
@ggeisler this is happening on every page except for the home page for me, as well as at various breakpoints.

![arclight-header](https://cloud.githubusercontent.com/assets/96776/26180068/02b00b20-3b1c-11e7-9d35-d738db778022.gif)

**Comment by ggeisler** [comment]
It looks like it is just hiding the scrollbar handle, so the white scroll gutter looks like unnecessary whitespace? Or am I not understanding the problem?

Here's what I see (gray scrollbar handle is visible):

![-_blacklight_search_results](https://cloud.githubusercontent.com/assets/101482/26180258/53a660fa-3b1d-11e7-9381-c996adc1747a.png)

**Comment by ggeisler** [comment]
Verified with @jkeck that this is indeed a real issue that needs looking into (a bit easier to see the problem if your OS is set to show scrollbars "automatically" instead of "always").
