### ISSUE TITLE
Search box/dropdown/button are misaligned on application's home page

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#359]
On the home page of the application, the search box is not the same hight as the search dropdown and the button

**Screenshot of bug**

![screen shot 2017-05-22 at 10 59 56 am](https://cloud.githubusercontent.com/assets/73732/26322098/6aa8952e-3ede-11e7-9329-3a0b9520b2db.png)

**Screenshot of another view without the same problem**

![screen shot 2017-05-22 at 11 03 16 am](https://cloud.githubusercontent.com/assets/73732/26322137/8384f68c-3ede-11e7-936c-3aebea307607.png)

**Comment by ggeisler** [comment]
I can fix this in my browser. By adding the class `navbar-search` to:

```
<form class="search-query-form navbar-search" role="search" action="http://localhost:3000/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">
```
I get this:

![blacklight](https://cloud.githubusercontent.com/assets/101482/26331157/4ca70ce2-3f04-11e7-9562-227874613896.png)

---
Which is what we want. 

However, I think the partial with that form code (`app/views/catalog/_search_within_form.html.erb`) comes from Blacklight? So I'm not sure what is the best strategy for fixing. Adding the class `navbar-search` to the same form element when used on a regular search results page doesn't seem to negatively affect the styling there, so it seems like adding it to the BL partial would be fine, but someone more familiar with Blacklight should probably make that call.
