### ISSUE TITLE
Single page view dropdown: display links to download PDF and EAD

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#371]
Refs #150. 

**Acceptance criteria** 

Given a EAD file used for indexing:

* Provide a configurable pathway to add a link to enable downloading an EAD version of the finding aid
* Provide a configurable pathway to add a link to enable downloading a PDF version of the finding aid

**Discussion**

* @ggeisler was suggesting that we use pre-created PDF files for this which is fine by me. Any suggestions about the pattern we should follow for this in terms of where to store them? 

**Mockup**

![arclight-mockups-mvp](https://cloud.githubusercontent.com/assets/73732/26071177/09e2359c-395c-11e7-8cf4-8ea21cc40269.jpg)

**Comment by ggeisler** [comment]
Suggestions for the select button, given we're only going to be showing the two download links for the time being:

- Rename button label to "Download"

![alpha_omega_alpha_archives__1894-1992_-_blacklight](https://cloud.githubusercontent.com/assets/101482/26365093/6a6819a0-3f9b-11e7-8988-0709ae6f3dcf.png)

- Options:

![alpha_omega_alpha_archives__1894-1992_-_blacklight 2](https://cloud.githubusercontent.com/assets/101482/26365125/7fd20f30-3f9b-11e7-8b26-a6e5ea002017.png)

---
We can revisit the label and options text after we add the single-page HTML option.

**Comment by ggeisler** [comment]
Minor addendum: if possible, it would be nice to include the download size of each file in the menu option:

- Collection PDF (452KB)
- Collection EAD (219KB)

I wouldn't call this critical if it is not easily feasible.

**Comment by drh-stanford** [comment]
@ggeisler what should we display if there's not a PDF or an EAD? i.e., should we omit the dropdown?

My PR will expect the PDFs to be named `unitid.pdf` and EADs to be named `unitid.xml` and they'll live in the `public/documents` directory.

**Comment by drh-stanford** [comment]
Here's what I have going -- the styling needs work (it's not right-aligned):

![screen shot 2017-05-30 at 2 21 26 pm](https://cloud.githubusercontent.com/assets/1861171/26607099/afb042ea-4549-11e7-9b9d-0c1ae87e192c.png)

**Comment by drh-stanford** [comment]
@anarchivist with Gary/Jennifer out, do you have an opinion on what we should display if there's not a PDF or an EAD? i.e., should we omit the dropdown?

**Comment by anarchivist** [comment]
Let's omit the dropdown if neither are available.
