### ISSUE TITLE
Add view toggle for truncated text in contents hierarchy

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/arclight#378]
We're currently truncating the scope note/other metadata shown for a component, as per the mockups. However, we don't give the user a way expand the truncated text to see the full metadata for the component.

I think we just need to add a simple toggle after the truncated text to provide this functionality. Something like this:

![milton_friedman_papers__1931-2006_-_blacklight](https://cloud.githubusercontent.com/assets/101482/26380917/2ae3ffe8-3fd6-11e7-93d0-ab17f0eefdb1.png)

----

![milton_friedman_papers__1931-2006_-_blacklight 2](https://cloud.githubusercontent.com/assets/101482/26380914/270d9d5c-3fd6-11e7-9c2d-3d834753a2f4.png)

**Comment by jkeck** [comment]
There are several places where this content is truncated.  We'll probably want to think about how we'll implement this type of feature holistically throughout the app.  (e.g. https://github.com/sul-dlss/arclight/blob/master/app/views/arclight/repositories/show.html.erb needs to have its abstract/scope truncated in the same way)
