### ISSUE TITLE
Add section heading(s) for components in contents hierarchy

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/arclight#379]
@anarchivist I don't think we omitted this intentionally, but please correct this ticket if it was discussed and I just missed or forgot the decision.

Currently we're showing a truncated version of metadata for a component (usually just the Scope and Contents note in our fixture/test data) in the hierarchy view. in the mockups (e.g, page 6 of the MVP version) we specified that the truncated text be prefaced with a section heading. I think this is worth adding, as it helps to define each component a bit better. Also, when collections have more and/or longer metadata than our test data, the section headings will be more informative.

So adding them something like this:

![milton_friedman_papers__1931-2006_-_blacklight 3](https://cloud.githubusercontent.com/assets/101482/26381259/5c19c97e-3fd8-11e7-904d-dc44e0761905.png)

Section headings should be `<h4>`s using this styling (though I can do this part):

``` css
color: #636c72;
font-size: $font-size-xs;
font-weight: normal;
text-transform: uppercase;
```

**Comment by anarchivist** [comment]
Thanks, @ggeisler!
