### ISSUE TITLE
Add documentation to the wiki on how to update an ArcLight app

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#381]
We need to provide some documentation about how someone can update an existing ArcLight application.

Context: Folks at the Bentley have tested ArcLight and ran into #361; we should now provide directions for them to follow about how to update their app make sure the fixes show up.

**Comment by drh-stanford** [comment]
See https://github.com/sul-dlss/arclight/wiki/Upgrading-your-ArcLight-application
