### ISSUE TITLE
Code updates to Repository show page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/arclight#394]
A) There is a "View all of our collections" link needs to be updated to actually go somewhere. I don't know the proper route so I just put in a placeholder (with a TODO in the code). The link should go to search results scoped to a) the current repository and b) Level = 'collection'

B) Since the repository title in the repository card links to the page we are on, it would be ideal to unlink the repository card title in just the repository show page context.

C) Ideally, the truncated text under the collection title should have a collapse/expand link, very similar to what is outlined for the contents hierarchy in #378.

![blacklight](https://cloud.githubusercontent.com/assets/101482/26430740/55fabeaa-40a4-11e7-8706-66d8a6f6fb30.png)

**Comment by jkeck** [comment]
WRT to `C`, I've added a comment to #378 to ensure that when we deal w/ adding a view more toggle here when we add this feature throughout the app.
