### ISSUE TITLE
Creators and names are not being indexed at the component level

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#399]
Discovered while reviewing WIP for #375 and #383. 

**Acceptance criteria**

* Given a collection that has components with creators
    * I should see the name of the creator(s) associated with that component in the Creator facet
    * Selecting that value in the Creator facet should filter to display the relevant component(s)
    * The associated collection for that component should not display in the search results unless it also has a Creator with the same exact value at the collection level
* Given a collection that has components with creators OR names in a `<controlaccess/>` tag:
    * I should see those names associated with that component in the Names facet
    * Selecting that value in the Names facet should filter to display the relevant component(s)
    * The associated collection for that component should not display in the search results unless it also has a Name with the same exact value at the collection level

**Comment by anarchivist** [comment]
#400 adds the necessary fixture data.

**Comment by anarchivist** [comment]
Made a minor change to the acceptance criteria.

**Comment by gordonleacock** [comment]
Done via "Subjects are not indexed at the component level #383"

**Comment by anarchivist** [comment]
Closed by #398
