### ISSUE TITLE
Display breadcrumb for hierarchy for each item/component in a search result

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#4]
Each item/component should be aware of how to get information about its parent components and collection. 

Acceptance criteria:
* Each component in a set of search results should display the breadcrumb, and link them to the relevant show views for those components

**Comment by anarchivist** [comment]
Mockup:

![results](https://cloud.githubusercontent.com/assets/73732/24984835/e6a240d4-1fa4-11e7-9c89-02c254582ca0.png)

**Comment by drh-stanford** [comment]
Also see #93 for the indexing implications
