### ISSUE TITLE
Collapse date histogram by default

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#409]
The date histogram takes up a lot of vertical space. Can we collapse it by default?

**Comment by ggeisler** [comment]
I was planning to see what I can do to reduce the height via CSS, but this makes sense to me until we can get a more reasonable display height.

**Comment by anarchivist** [comment]
I think @mejackreed mentioned that this might be tricky, since it's generating the height using the golden ratio of the element's width.

**Comment by ggeisler** [comment]
Yeah, but a little bit of experimenting makes it seem like it's overridable via CSS, I'm just not sure if it will cause unreasonable distortion or other unknown problems. So collapsing seems like a good idea and _if_ I can get something better we can revisit.
