### ISSUE TITLE
Rework embedded digital object display for collections and components

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#416]
This is a substantial reworking of the behavior around digital objects per discussion on #332 and #277.

Refs #242, #237 and #278. 

**Acceptance criteria**

* Remove the "Online content" sidebar block for both collections and components. 
* Add a new "Online content" tab for both collection and component views. 
* For collection-level views:
     * For each digital object at the collection level: 
          * If the object is embeddable, display an embedded viewer for that object
          * If the object is not embeddable, display a link to the digital object 
              * Add a link to the URI identified in the `href` link with the text (in order of preference): as
                   * the `<dao/>`'s `title` attribute OR its `<daodesc/>` 
                   * the `<dao/>`'s  `<daodesc/>` 
                   * the `<dao/>`'s  `href` attribute
     * ~If there are no objects at the collection level, but there are digital objects at the component level, display list of components with digital objects~ (see #416)
     * If there are no collection or component level digital objects:
          * The tab should be inactive and read "No online content"
* For component-level views:
     * For each digital object associated with a component: 
          * If the object is embeddable, display an embedded viewer for that object
          * If the object is not embeddable, display a link to the digital object 
              * Add a link to the URI identified in the `href` link with the text (in order of preference): as
                   * the `<dao/>`'s `title` attribute OR its `<daodesc/>` 
                   * the `<dao/>`'s  `<daodesc/>` 
                   * the `<dao/>`'s  `href` attribute   
     * If there are no digital objects at that level:
          * The tab should be inactive and read "No online content"

**Screenshots**
### Collection-level online content
![viewer](https://cloud.githubusercontent.com/assets/101482/26180086/21176fa4-3b1c-11e7-9aa8-e5071db09c6f.png)

###  Component-level online content
![all-online-content](https://cloud.githubusercontent.com/assets/101482/26180091/2d73b488-3b1c-11e7-851c-929e68d2c344.png)

**Comment by jkeck** [comment]
A few questions looking over this ticket:

1. This ticket assumes that there is an `Overview` and `Contents` tab on the component view.  Currently we have two sections (not in a tabbed UI) that is the Metadata and the Collection Context.  Is part of the acceptance criteria for this ticket to move those sections into tabs for the Component display page?
1. Do we have a fixture w/ an oEmbeddable digital object at the collection level?
1. When a non-embeddable object is encountered, this ticket says to "display a link to the digital object".  How should this link manifest itself? Just line-break delimited links in the `Online content` tab?
1. How should multiple digital objects be handled at either component or collection level?

**Comment by anarchivist** [comment]
> Does this ticket assume that there is an `Overview` and `Contents` tab on the component view?  Currently we have two sections (not in a tabbed UI) that is the Metadata and the Collection Context.  Is part of the acceptance criteria for this ticket to move those sections into tabs for the Component display page?  Otherwise, we haven't defined how the link will be rendered in the absence of an oEmbeddable object. 

I think this assumes that what currently shows on the component detail page is the `Overview` tab. This would add a new `Online content` tab to the component detail page, following a similar pattern as to what we've proposed for digital objects at the collection level. 

> Do we have a fixture w/ an oEmbeddable digital object at the collection level?

I will update one of the fixtures to have one. 

> When a non-embeddable object is encountered, this ticket says to "display a link to the digital object". How should this link manifest itself? Just line-break delimited links in the `Online content` tab?

Line-break delimited would be OK, perhaps list-item-delimited wrapped in a `<ul/>` would be better? In any case, yes, they would show up on `Online content` tab. 

> How should multiple digital objects be handled at either component or collection level?

My first proposal:

* If the first one is embeddable, show the first one, then display the list of all digital objects (including the embedded one).
* If the first one is not embeddable, just show the list as normal. 

Presuming we go this route, can we make sure that we add comments that document this behavior in the appropriate places?

**Comment by anarchivist** [comment]
#427 adds an embeddable collection-level digital object.
