### ISSUE TITLE
Index EAD from url (and file of urls)

### ISSUE THREAD

**Issue by mark-cooper** [sul-dlss/arclight#418]
Just dipping my toe into Arclight and indexing some EADs to get a feel for it. Already looking pretty slick!

I added a couple of rake tasks to extend the indexing options:

https://github.com/sul-dlss/arclight/compare/master...mark-cooper:index_from_url?expand=1

Would this be something you'd welcome as a PR? I think it's immediately useful for testing EAD from a variety of online sources without having to download the files locally. Down the road it could also be one approach for ingesting from remote EAD sources (even perhaps ArchivesSpace), and therefore may be relevant to:

https://github.com/sul-dlss/arclight/issues/85
https://github.com/sul-dlss/arclight/issues/110

But feel free to close this issue if you're not looking for such contributions at this time :smile:

**Comment by anarchivist** [comment]
Hi @mark-cooper - I haven't talked to the rest of the team yet, but please feel free to submit a PR. Thanks!
