### ISSUE TITLE
Demo server should serve up robots.txt

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#448]
Even though we have the consent of folks to use their data, we probably shouldn't have search engines index the finding aids there. We have one in the app which I just updated (see sul-dlss/arclight-demo#44), but it's not getting served up - https://arclight-demo.projectblacklight.org/robots.txt returns a 404.

**Comment by anarchivist** [comment]
I'll add that it seems to work for `demo.projectblacklight.org`.

**Comment by jkeck** [comment]
We've tracked down the issue to needing to set an env var on the demo-site's AWS instance: https://github.com/sul-dlss/arclight-demo/blob/master/config/environments/production.rb#L19

Unfortunately, setting this on AWS isn't working as expected at the moment.  DevOps is going to look into this early next week.

If, for whatever reason, that doesn't pan out, we can always remove the env var requirement in our `production.rb` but this should be a last resort as this is standard rails behavior.

**Comment by anarchivist** [comment]
implemented
