### ISSUE TITLE
Facet and refine search results by names

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#5]
* Includes creators and names included as controlled access terms
* Includes personal and corporate names in a single "Names" facets

Ref: req 1.4 ("Facet and refine search results by agent/creator")

**Comment by drh-stanford** [comment]
Are the personal and corporate names supposed to be in the *same* facet or distinct facets?

**Comment by drh-stanford** [comment]
## Combined "Names" facet which pulls from corpname, famname, name, and persname

![screen shot 2017-04-14 at 1 27 08 pm](https://cloud.githubusercontent.com/assets/1861171/25055172/1d1df140-2116-11e7-8ddc-660a60aa4f5c.png)

**Comment by anarchivist** [comment]
> Are the personal and corporate names supposed to be in the _same_ facet or distinct facets?

They should be in the same facet.
