### ISSUE TITLE
Restyle non-clickable elements

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#535]
Originally reported by the Michigan team. Elements that are used for labels (e.g. the "online content" button) appear to be clickable because of their prominence and styling.  See also #488 for the converse issue; potential dupe of #509 

Feedback from estimation process:

* Albany: We found this issue also, but not sure if it's a symptom of broader issues with the tab interface.

**Comment by ggeisler** [comment]
I suggest we close this ticket (or mark it clearly as a story ticket) in favor of:

[#509](#509) - Improve styling of "Online content" label
[#520](#520) - Improve styling of tabs on component page

(I'm just worried that multiple tickets that effectively address the same topic will make it more difficult to keep track of what we need to focus on, and prefer design tickets that state what needs to be addressed more specifically.)
