### ISSUE TITLE
Facet and refine search results by dates

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#8]
Users should be able to facet and refine search results by dates.

**Acceptance criteria**

* The facet should display as a range facet
* The range for the facet query should be controllable by two sliders OR by two text entry widgets
* Fixture data requirement: Must contain normalized dates #151
* NOTE that the "top-level" date histogram is another ticket: #141
- - -

* Ref: req 1.6
* Category: 1. Core Discovery
* Subcategory: Browse

**Comment by mejackreed** [comment]
If #160 is accepted, then this can proceed using the BL RL branch for BL7

**Comment by jkeck** [comment]
@anarchivist looking over http://eadiva.com/2/unitdate/ as well as https://github.com/sul-dlss/arclight/commit/53c1b0b6d909003b5d9fe92073b276d12c9d3346 I think it might be helpful to know what kind of dates we want to be able to handle initially to consider this feature acceptable.

An initial proposal could be to just handle `unitdate` elements w/ a `normal` attribute.  If that was 👌  then I think we would just need to know what formats we want to support (i.e. `YYYYMMDD`, `YYYY/YYYY`, etc.) and what is the desired behaviors for the various values that can be present in the `type` and `certainty` attributes.

**Comment by anarchivist** [comment]
:+1: to requiring `normal` attributes on `unitdates` to showing on the facet. 

For this ticket, I would focus on `YYYY` and `YYYY/YYYY` dates, and would punt on changes in behavior for `type` and `certainty`. At some point, we should support `YYYYMMDD`, `YYYYMM`, and the associated ranges, but I expect that the level of granularity exposed by the facet would only be at the year-level.
