### ISSUE TITLE
Represent hierarchy in index documents

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#93]
* Collections should know (at least) their immediate child components
* Components should know their parent collection, and immediate parent and immediate child components when applicable

See also #4

**Comment by mejackreed** [comment]
An example (not saying the way to do this) of this being done in GeoBlacklight: https://github.com/geoblacklight/geoblacklight/pull/506

**Comment by jkeck** [comment]
Neat!  I think some of the spirit of this ticket (or perhaps described in another ticket) is that we want to use this opportunity to look into graph traversal.  If that doesn't pan out, I think this is a great solution to something along these lines.

**Comment by mejackreed** [comment]
Sure thing. I think that also has significant implications on https://github.com/sul-dlss/arclight/issues/91 and implicated indexing code.

**Comment by mejackreed** [comment]
Might be relevant too: https://www.slideshare.net/lucidworks/working-with-deeply-nested-documents-in-apache-solr-presented-by-anshum-gupta-alisa-zhila-ibm-watson

**Comment by drh-stanford** [comment]
The data for the requirements on this ticket are already in the indexing code, but it does not work for more than 1 level up/down at each node.

See https://github.com/awead/solr_ead/blob/8cf7ffaa66e0e4c9c0b12f5646d6c2e20984cd99/lib/solr_ead/behaviors.rb#L65-L77

Should we create another ticket for dealing with n levels of hierarchy? We can code up the 1 level up/down as-is now...

**Comment by mejackreed** [comment]
Yeah I've been looking at this. I think 1 level of hierarchy might be a good start here? Let's see where that takes us?

**Comment by mejackreed** [comment]
@drh-stanford I've found that the indexing code is working correctly when I've added in a new component level. Not sure if I did this right but here is what I did:

https://gist.github.com/mejackreed/1a5d59404b2f8693b1c27c63e225054b#file-alphaomegaalpha-xml-L199-L208

**Comment by drh-stanford** [comment]
That XML looks fine. Why didn't the indexing code work _without_ that XML? Am I following you correctly?

**Comment by mejackreed** [comment]
For our `alphaomegaalpha.xml` example everything seems fine

**Comment by mejackreed** [comment]
Current indexing reflects the following (out of the box solr_ead):

 - children know about all of their parents

**Comment by mejackreed** [comment]
I'm also curious about the need here: Why do components need to know about all of their children? Can we call out the places this is needed? There may be other approaches that work here rather than needed to also index the relationships both ways.

**Comment by jkeck** [comment]
I think this is most likely coming from the design documents (and where some of my questions around navigational context in the hierarchy come from).  I think the need is that in the context of a parent component, we need to have the ability to display its children.

It seems like we can most likely do this w/ the relationships as solr_ead has them and have to display hierarchy/relationships asynchronously when necessary (which is what I think you've done in GeoBlacklight?).

I think we can probably get away with doing that, although a child knowing its entire ancestor tree will be useful for things like building breadcrumbs.

**Comment by mejackreed** [comment]
Agree. FWIW, its my understanding that a child already knows all of its parents

**Comment by jkeck** [comment]
Does this sound good @anarchivist?  If so, then I think we can consider this done.

**Comment by anarchivist** [comment]
:+1: to a child knowing all of its ancestors.

@mejackreed 💬  

> I'm also curious about the need here: Why do components need to know about all of their children? Can we call out the places this is needed? There may be other approaches that work here rather than needed to also index the relationships both ways.

I'm not sure I called this out specifically. My intent was that a collection or component needs to know  all of its _immediate_ children, not all of its children. @jkeck is right that:

> I think this is most likely coming from the design documents (and where some of my questions around navigational context in the hierarchy come from). I believe the need is that in the context of a parent component, we need to have the ability to display its children.

 See, for example the mockups on #149.

**Comment by jkeck** [comment]
@anarchivist so do you feel that this is completed as described?

I believe the indexing is done in such a way that we **can** know a parent's direct children although there is nothing in the UI to display them.  So if the "index documents" we refer to when we say "Represent hierarchy in index documents" is the solr documents, then I think we've met the acceptance criteria for this ticket.

**Comment by anarchivist** [comment]
Yes, I think this is adequate. I'd intended this to refer to Solr documents, so I'll close for now. Thanks!
